// Stronger geometric-completion obstruction: the old winning hull is outside
// the OPEN parent itself, so even additional sites inside the parent cannot help.
#include "geometric_overlay.hpp"
int main(int argc,char**argv){try{need(argc==5,"base one_pose target fresh_output");need(!std::filesystem::exists(argv[4]),"fresh output");auto raw=file_raw(argv[1]),pr=file_raw(argv[2]);auto d=json_raw(raw);auto ps=arr(json_raw(pr));need(ps.size()==1,"one pose");auto c=validate(d);Q T(argv[3]);need(Q(0)<T,"positive target");Q A=c.L/T,t(ps[0].get<std::string>("t"));V p{Q(ps[0].get<std::string>("cx")),Q(ps[0].get<std::string>("cy"))};auto count=geometric_counts(c,d,A,t,p);I fee=counts_fee(d,count);need(17*fee<c.budget,"counterexample premise");auto cs=trig(t);Z C=t.d*t.d-t.n*t.n,S=2*t.d*t.n;std::vector<bool>hit;for(auto z:c.physical){Q dx=Q(z[0],c.D)-p.x,dy=Q(z[1],c.D)-p.y;hit.push_back(qa(cs[0]*dx+cs[1]*dy)<A/Q(2)&&qa(cs[0]*dy-cs[1]*dx)<A/Q(2));}
 std::ofstream o(argv[4]);o<<"{\"base_sha256\":\""<<sha256(raw)<<"\",\"pose_sha256\":\""<<sha256(pr)<<"\",\"target\":\""<<T.str()<<"\",\"witnesses\":[";bool first=true;int fired=0,blocked=0,weak=0;std::vector<int>miss;
 for(size_t fi=0;fi<c.features.size();fi++){auto&g=c.features[fi];if(!g.weight)continue;need((g.rules.empty()?std::accumulate(g.co.begin(),g.co.end(),I(0))/g.threshold:1)==1,"capacity one");int mask=0;for(size_t k=0;k<g.ids.size();k++)if(hit[g.ids[k]])mask|=1<<k;if(fires(mask,g.co,g.threshold,g.rules)){fired++;continue;}bool ok=false;
 for(int w=1;w<(1<<g.ids.size())&&!ok;w++){if(!fires(w,g.co,g.threshold,g.rules))continue;bool minimal=true;for(size_t k=0;k<g.ids.size();k++)if((w&(1<<k))&&fires(w^(1<<k),g.co,g.threshold,g.rules))minimal=false;if(!minimal)continue;std::vector<Point>v,axes{{C,S},{-S,C}};for(size_t k=0;k<g.ids.size();k++)if(w&(1<<k))v.push_back(c.physical[g.ids[k]]);for(size_t i=0;i<v.size();i++)for(size_t j=i+1;j<v.size();j++)axes.push_back({v[i][1]-v[j][1],v[j][0]-v[i][0]});
 for(auto n:axes){if(n[0]==0&&n[1]==0)continue;Z gg=gcdz(n[0],n[1]);n[0]/=gg;n[1]/=gg;for(int s:{1,-1}){Z nx=s*n[0],ny=s*n[1],lo=nx*v[0][0]+ny*v[0][1];for(auto z:v)lo=std::min(lo,Z(nx*z[0]+ny*z[1]));Q support=(Q(nx)*p.x+Q(ny)*p.y+A/Q(2)*(qa(Q(nx)*cs[0]+Q(ny)*cs[1])+qa(Q(ny)*cs[0]-Q(nx)*cs[1])))*Q(c.D);if(!(support<=Q(lo)))continue;ok=true;blocked++;if(support==Q(lo))weak++;if(!first)o<<',';first=false;o<<"{\"feature_image\":"<<fi<<",\"captured_mask\":"<<mask<<",\"old_winning_mask\":"<<w<<",\"normal\":[\""<<nx<<"\",\""<<ny<<"\"],\"closed_parent_support\":\""<<support.str()<<"\",\"winning_support_min\":\""<<lo<<"\"}";break;}if(ok)break;}}
 if(!ok)miss.push_back(fi);
 }
 o<<"],\"fired_images\":"<<fired<<",\"blocked_losing_images\":"<<blocked<<",\"boundary_separations\":"<<weak<<",\"uncovered_images\":";numbers(o,miss);o<<",\"open_fee\":"<<fee<<",\"budget_units\":"<<c.budget<<",\"surplus\":"<<17*fee-c.budget<<",\"status\":\""<<(miss.empty()?"PASS_CPP_PARENT_SEPARATION_COMPLETION_OBSTRUCTION":"INCOMPLETE_PARENT_SEPARATION_OBSTRUCTION")<<"\"}\n";std::cout<<"fired="<<fired<<" blocked="<<blocked<<" uncovered="<<miss.size()<<std::endl;return miss.empty()?0:2;
 }catch(const std::exception&e){std::cerr<<"REJECT "<<e.what()<<'\n';return 1;}}
