'use strict';
// Independent certificate check via four explicit parent vertices, not the C++
// absolute-projection support formula. Even newly introduced sites cannot cross
// a certified exterior support line while lying in the open parent.
const e=require('./exact_model.js');const{fs,need,sha,Q,parse,add,sub,mul,div,le,str}=e;
const[bp,pp,cp,out]=process.argv.slice(2);need(bp&&pp&&cp&&out&&!fs.existsSync(out),'base pose cpp fresh-output');let m=e.loadModel(bp),pb=fs.readFileSync(pp),poses=JSON.parse(pb),cb=fs.readFileSync(cp),c=JSON.parse(cb);need(c.base_sha256===m.sha&&c.pose_sha256===sha(pb)&&poses.length===1,'source binding');let p=poses[0],t=parse(p.t),x=parse(p.cx),y=parse(p.cy),A=div(m.L,parse(c.target)),half=div(A,Q(2)),tt=mul(t,t),den=add(Q(1),tt),co=div(sub(Q(1),tt),den),si=div(mul(Q(2),t),den),vertices=[];
for(let a of[-1,1])for(let b of[-1,1])vertices.push([add(x,mul(half,sub(mul(Q(a),co),mul(Q(b),si)))),add(y,mul(half,add(mul(Q(a),si),mul(Q(b),co))))]);let hits=e.captures(m,p,A).hit,rows=e.counts(m,hits),fee=e.fee(m,rows),wits=new Map;for(let w of c.witnesses){need(!wits.has(w.feature_image),'duplicate image witness');wits.set(w.feature_image,w);}let fi=0,fired=0,blocked=0,boundary=0;
for(let gg of m.groups)for(let g of gg){let id=fi++;if(g.weight===0n)continue;need((g.rules.length?1:Math.floor(g.co.reduce((a,b)=>a+b,0)/g.k))===1,'budget-one premise');let mask=0;for(let i=0;i<g.ids.length;i++)if(hits[g.ids[i]])mask|=1<<i;if(e.fires(g,mask)){fired++;need(!wits.has(id),'extra fired witness');continue;}let w=wits.get(id);need(w&&w.captured_mask===mask,'missing/wrong mask');let wm=w.old_winning_mask;need(Number.isInteger(wm)&&wm>0&&wm<(1<<g.ids.length)&&e.fires(g,wm),'old win');let n=w.normal.map(BigInt);need(n.length===2&&(n[0]!==0n||n[1]!==0n),'nonzero separating normal');let vp=vertices.map(z=>mul(add(mul(Q(n[0]),z[0]),mul(Q(n[1]),z[1])),Q(m.D))),sup=vp.reduce((a,b)=>le(a,b)?b:a),values=g.ids.filter((_,k)=>wm&(1<<k)).map(i=>n[0]*m.pts[i][0]+n[1]*m.pts[i][1]),low=values.reduce((a,b)=>a<b?a:b);need(str(sup)===str(parse(w.closed_parent_support))&&low===BigInt(w.winning_support_min),'support values');need(le(sup,Q(low)),'winning hull not separated from open parent');if(sup[0]===low*sup[1])boundary++;blocked++;wits.delete(id);}
need(wits.size===0&&c.uncovered_images.length===0&&fired===c.fired_images&&blocked===c.blocked_losing_images&&boundary===c.boundary_separations,'exhaustive image counts');need(fee===BigInt(c.open_fee)&&m.M===BigInt(c.budget_units)&&17n*fee-m.M===BigInt(c.surplus)&&17n*fee<m.M,'exact counterexample');let result={status:'PASS_INDEPENDENT_BIGINT_PARENT_SEPARATION_COMPLETION_OBSTRUCTION',base_sha256:m.sha,pose_sha256:sha(pb),cpp_sha256:sha(cb),target:c.target,fired_images:fired,blocked_losing_images:blocked,boundary_separations:boundary,open_fee:String(fee),budget_units:String(m.M),surplus:String(17n*fee-m.M),scope:'unchanged primitive weights; each original winning subset remains sufficient; each primitive uses nonempty pairwise-intersecting winning convex hulls. Any extra sites allowed. Does NOT exclude reweighting, replacement dropping old triggers, new budget/resources, or other capacity arguments.'};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
