"""Portable golden sessions for the native rectangle-density CLI."""

from __future__ import annotations

import difflib
import hashlib
import json
import math
import os
import shlex
import subprocess
import sys
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any

import pytest

PACKING = Path(__file__).parents[1]
GOLDEN = PACKING / "tests/golden/rectangle-density-cli"
UPDATE_ENV = "UPDATE_RECTANGLE_DENSITY_CLI_GOLDEN"


@dataclass(frozen=True, slots=True)
class Scenario:
    key: str
    name: str
    arguments: tuple[str, ...]
    exit_code: int
    status: str


@dataclass(frozen=True, slots=True)
class Session:
    scenario: Scenario
    stdout: str
    stderr: str
    exit_code: int
    payload: dict[str, Any]
    input_sha256: str
    input_bytes: int


SCENARIOS = (
    Scenario(
        "complete",
        "complete analytic verification",
        (
            "resources/web/wand125-tools-2026-09-29/native-analytic-control.json",
            "--n",
            "3",
            "--side",
            "3/2",
            "--angles",
            "all",
            "--max-nodes-per-angle",
            "10000",
            "--max-depth",
            "20",
            "--max-seconds",
            "30",
        ),
        0,
        "VERIFIED",
    ),
    Scenario(
        "partial",
        "selected directions remain partial",
        (
            "resources/web/wand125-tools-2026-09-29/native-analytic-control.json",
            "--n",
            "3",
            "--angles",
            "0,1",
            "--max-seconds",
            "30",
        ),
        2,
        "PARTIAL",
    ),
    Scenario(
        "inconclusive",
        "work cap remains inconclusive",
        (
            "resources/web/wand125-tools-2026-09-29/native-analytic-control.json",
            "--n",
            "3",
            "--angles",
            "1",
            "--max-nodes-per-angle",
            "0",
            "--max-seconds",
            "30",
        ),
        2,
        "INCONCLUSIVE",
    ),
    Scenario(
        "counterexample",
        "exact coverage counterexample fails",
        (
            "tests/fixtures/rectangle-density-cli/counterexample.json",
            "--n",
            "3",
            "--angles",
            "0",
            "--max-seconds",
            "30",
        ),
        1,
        "COUNTEREXAMPLE",
    ),
    Scenario(
        "refused",
        "mass admission failure is refused",
        (
            "resources/web/wand125-tools-2026-09-29/receipts/admission-scaled.json",
            "--n",
            "1",
            "--side",
            "3/2",
            "--max-seconds",
            "30",
        ),
        1,
        "REFUSED",
    ),
)


def _run(scenario: Scenario) -> Session:
    command = (sys.executable, "-m", "devtools.verify_rectangle_density", *scenario.arguments)
    input_path = PACKING / scenario.arguments[0]
    input_data = input_path.read_bytes()
    environment = {
        "PATH": os.environ.get("PATH", ""),
        "PYTHONHASHSEED": "0",
        "PYTHONIOENCODING": "utf-8",
    }
    for key in ("TMPDIR", "UV_CACHE_DIR", "CARGO_TARGET_DIR"):
        if key in os.environ:
            environment[key] = os.environ[key]
    completed = subprocess.run(
        command,
        cwd=PACKING,
        env=environment,
        capture_output=True,
        timeout=10,
        check=False,
    )
    stdout = completed.stdout.decode("utf-8")
    stderr = completed.stderr.decode("utf-8")
    payload: dict[str, Any] = json.loads(stdout)
    assert completed.returncode == scenario.exit_code
    assert payload["status"] == scenario.status
    assert stderr == ""
    assert input_path.read_bytes() == input_data
    return Session(
        scenario,
        stdout,
        stderr,
        completed.returncode,
        payload,
        hashlib.sha256(input_data).hexdigest(),
        len(input_data),
    )


@pytest.fixture(scope="module")
def sessions() -> tuple[Session, ...]:
    return tuple(_run(scenario) for scenario in SCENARIOS)


def _render(session: Session) -> str:
    scenario = session.scenario
    update_command = f"{UPDATE_ENV}=1 uv run --frozen pytest"
    update_command += " tests/test_rectangle_density_cli_golden.py"
    command = shlex.join(
        ("python", "-m", "devtools.verify_rectangle_density", *scenario.arguments)
    )
    normalization = "Normalization: absolute Python executable -> python;"
    normalization += " working directory -> packing."
    header = "\n".join(
        (
            "Native rectangle-density CLI golden session",
            f"Scenario: {scenario.name}",
            "Generated by: tests/test_rectangle_density_cli_golden.py",
            f"Update: {update_command}",
            normalization,
            "No stdout or stderr byte is normalized.",
            "",
            f"Command: {command}",
            f"Exit: {session.exit_code}",
            f"Input SHA-256: {session.input_sha256}",
            f"Input bytes: {session.input_bytes}",
            f"Stdout UTF-8 bytes: {len(session.stdout.encode())}",
            f"Stderr UTF-8 bytes: {len(session.stderr.encode())}",
            "",
        )
    )
    return (
        f"{header}Stdout begin:\n"
        f"{session.stdout}Stdout end.\n\n"
        f"Stderr begin:\n{session.stderr}Stderr end.\n"
    )


def _check_or_update(path: Path, actual: str, *, update: bool) -> None:
    if update:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="") as stream:
            stream.write(actual)
        return
    if not path.is_file():
        raise AssertionError(f"no golden at {path}; set {UPDATE_ENV}=1 to create it")
    with path.open(encoding="utf-8", newline="") as stream:
        expected = stream.read()
    if actual != expected:
        difference = "".join(
            difflib.unified_diff(
                expected.splitlines(keepends=True),
                actual.splitlines(keepends=True),
                fromfile=str(path),
                tofile="current CLI session",
            )
        )
        raise AssertionError(f"rectangle-density CLI golden differs:\n{difference}")


def _assert_semantics(sessions: tuple[Session, ...]) -> None:
    complete, partial, inconclusive, counterexample, refused = (
        session.payload for session in sessions
    )
    checker = PACKING / "src/sqpack/rectangle_density.py"
    checker_sha = hashlib.sha256(checker.read_bytes()).hexdigest()
    assert complete["checker_source_sha256"] == checker_sha
    assert all(
        session.payload.get("checker_source_sha256") == checker_sha for session in sessions[:-1]
    )
    for session in sessions[:-1]:
        assert session.payload["candidate_sha256"] == session.input_sha256
    assert complete["mass"] == "1683003/625000"
    assert complete["mass_below_n"] == "191997/625000"
    assert complete["angle_count"] == complete["requested_angle_count"] == 201
    assert len(complete["angles"]) == 201
    assert [angle["index"] for angle in complete["angles"]] == list(range(201))
    assert all(angle["status"] == "VERIFIED" for angle in complete["angles"])
    assert all(angle["unresolved_leaves"] == 0 for angle in complete["angles"])
    threshold = Fraction(complete["threshold"])
    assert all(Fraction(angle["lower_bound"]) >= threshold for angle in complete["angles"])
    assert partial["angle_count"] == 2
    assert partial["requested_angle_count"] == 2
    assert inconclusive["angles"][0]["unresolved_leaves"] == 1
    witness = counterexample["angles"][0]["counterexample"]
    assert Fraction(witness["value"]) == Fraction(298621587, 25000000000)
    assert (Fraction(witness["x"]), Fraction(witness["y"])) == (
        Fraction(3, 4),
        Fraction(3, 4),
    )
    assert counterexample["angles"][0]["unresolved_leaves"] == 8
    assert "mass" in refused["error"]


def test_rectangle_density_cli_golden(sessions: tuple[Session, ...]) -> None:
    _assert_semantics(sessions)
    update = os.environ.get(UPDATE_ENV) == "1"
    for session in sessions:
        golden = GOLDEN / f"{session.scenario.key}.txt"
        _check_or_update(golden, _render(session), update=update)


def test_rectangle_density_cli_semantics(sessions: tuple[Session, ...]) -> None:
    _assert_semantics(sessions)


def test_timing_is_opt_in_and_preserves_cli_decisions(sessions: tuple[Session, ...]) -> None:
    for original in (sessions[1], sessions[2], sessions[4]):
        scenario = original.scenario
        timed = _run(
            Scenario(
                scenario.key,
                scenario.name,
                (*scenario.arguments, "--timing"),
                scenario.exit_code,
                scenario.status,
            )
        )
        timing = timed.payload.pop("timing")
        assert timed.payload == original.payload
        assert "timing" not in original.payload
        assert timing["wall_clock"] == "perf_counter"
        assert timing["cpu_clock"] == "process_time"
        assert timing["excluded"] == [
            "module_startup_and_argument_parsing",
            "receipt_build_serialization_and_output",
        ]
        phases = timing["phases"]
        expected = {"input_read_hash", "admission"}
        if scenario.status != "REFUSED":
            expected |= {"verification", "source_recheck"}
        assert set(phases) == expected
        for phase in phases.values():
            assert set(phase) == {"wall_seconds", "process_cpu_seconds"}
            assert all(math.isfinite(value) and value >= 0 for value in phase.values())


def test_golden_updates_only_when_explicitly_requested(tmp_path: Path) -> None:
    snapshot = tmp_path / "golden.md"
    with snapshot.open("w", encoding="utf-8", newline="") as stream:
        stream.write("old\n")

    with pytest.raises(AssertionError, match="golden differs"):
        _check_or_update(snapshot, "new\n", update=False)
    with snapshot.open(encoding="utf-8", newline="") as stream:
        assert stream.read() == "old\n"

    _check_or_update(snapshot, "new\n", update=True)
    with snapshot.open(encoding="utf-8", newline="") as stream:
        assert stream.read() == "new\n"
