// Exact finite classification and partial packings; graph edges need fresh tree receipts.
#include "../../followup_c028/src/common.hpp"
#include <map>
static Q gap(const Pose&a,const Q&A,const Pose&b,const Q&B){Q best=-Q(1000);for(V n:{frame(a.t),perp(frame(a.t)),frame(b.t),perp(frame(b.t))})best=qmax(best,qa(dot(n,a.c-b.c))-radius(a,A,n)-radius(b,B,n));return best;}
static int pop(unsigned m){return __builtin_popcount(m);}
static bool member(const Pose&p,const J&g,const std::array<std::array<Q,2>,3>&root){std::array<Q,3>v{p.c.x,p.c.y,p.t};std::array<std::vector<int>,3>poss;for(int d=0;d<3;d++){Q z=Q(64)*(v[d]-root[d][0])/(root[d][1]-root[d][0]);if(z<Q(0)||z>Q(64))return false;int k=(z.numerator()/z.denominator()).convert_to<int>();if(k<64)poss[d].push_back(k);if(z==Q(k)&&k>0)poss[d].push_back(k-1);}std::set<int>keys;for(auto&k:ja(g.get_child("cell_keys")))keys.insert(std::stoi(k.data()));for(int x:poss[0])for(int y:poss[1])for(int t:poss[2])if(keys.count((x*64+y)*64+t))return true;return false;}
int main(int n,char**v){try{
 need(n==7,"USAGE_SPEC_ATLAS_FRONTIER_GRAPH_RECEIPTS_OUTPUT");need(!std::filesystem::exists(v[6]),"FRESH_OUTPUT_REQUIRED");J sj=readj(v[1]),aj=readj(v[2]),fj=readj(v[3]),j=readj(v[4]);need(j.get<std::string>("schema")=="n17.c029.joint-graph.v1","SCHEMA");Q L=getq(sj,"L"),T=getq(sj,"cap"),A=L/T;need(getq(aj,"cap")==T&&getq(aj,"parent_side")==A,"TARGET_IDENTITY");Pose anc=pose(j.get_child("anchor")),ref=pose(sj.get_child("anchor"));need(anc.c.x==ref.c.x&&anc.c.y==ref.c.y&&anc.t==ref.t,"ANCHOR_IDENTITY");need(fits(anc,A,L),"ILLEGAL_ANCHOR");Q alpha=Q(1)-getq(sj,"epsilon"),step=(T-Q(2)*alpha)/Q(3);std::vector<V>grid;for(int y=0;y<4;y++)for(int x=0;x<4;x++)grid.push_back({A*(alpha+Q(x)*step),A*(alpha+Q(y)*step)});unsigned am=0;for(int k=0;k<16;k++)if(point_margin(anc,A,grid[k])>Q(0))am|=1u<<k;need(am==2,"ANCHOR_POINT_ID");
 std::array<std::array<Q,2>,3>root;auto rr=ja(aj.get_child("root"));need(rr.size()==3,"ROOT_SHAPE");for(int d=0;d<3;d++){auto r=ja(rr[d]);need(r.size()==2,"ROOT_SHAPE");root[d]={qr(r[0].data()),qr(r[1].data())};}auto groups=ja(fj.get_child("components"));need(groups.size()==18,"COMPONENT_COUNT");for(int g=0;g<18;g++){auto r=ja(groups[g].get_child("center_rectangle"));need(r.size()==2,"CENTER_RECTANGLE");auto x=ja(r[0]),y=ja(r[1]);need(x.size()==2&&y.size()==2,"CENTER_RECTANGLE");Q w=qr(x[1].data())-qr(x[0].data()),h=qr(y[1].data())-qr(y[0].data());need(w>Q(0)&&h>Q(0)&&w*w+h*h<A*A,"COMPONENT_CAPACITY");}
 std::array<unsigned,18>adj{};std::set<int>seen;std::vector<std::array<int,2>>edges;long long pairnodes=0,ownernodes=0;
 auto pairid=[&](const J&r){auto z=ja(r);need(z.size()==2,"PAIR_SHAPE");int a=std::stoi(z[0].data()),b=std::stoi(z[1].data());need(0<=a&&a<b&&b<18&&seen.insert(a*18+b).second,"PAIR_RANGE_OR_DUPLICATE");return std::array<int,2>{a,b};};
 for(auto&e:ja(j.get_child("edges"))){auto p=pairid(e);edges.push_back(p);adj[p[0]]|=1u<<p[1];adj[p[1]]|=1u<<p[0];std::ostringstream name;name<<v[5]<<"/pair_"<<std::setfill('0')<<std::setw(2)<<p[0]<<'_'<<std::setw(2)<<p[1]<<"_cpp.json";J r=readj(name.str());auto pr=ja(r.get_child("pair"));need(r.get<std::string>("status")=="PASS_CONTINUOUS_PAIR_EXCLUSION"&&pr.size()==2&&std::stoi(pr[0].data())==p[0]&&std::stoi(pr[1].data())==p[1]&&getq(r,"cap")==T,"PAIR_RECEIPT");pairnodes+=r.get<long long>("nodes");}
 need(edges.size()==17,"EDGE_COUNT");for(auto [g,k]:std::array<std::array<int,2>,2>{{{{0,0}},{{10,2}}}}){std::ostringstream name;name<<v[5]<<"/fullowner_"<<std::setfill('0')<<std::setw(2)<<g<<'_'<<std::setw(2)<<k<<"_cpp.json";J r=readj(name.str());need(r.get<std::string>("status")=="PASS_COMPONENT_FORCES_UNOWNED_POINT"&&r.get<int>("component")==g&&r.get<int>("point")==k&&getq(r,"cap")==T,"HOLE_RECEIPT");ownernodes+=r.get<long long>("nodes");}
 int compat=0;Q minsep=Q(1000),minavoid=Q(1000);for(auto&r:ja(j.get_child("compatible_pairs"))){auto p=pairid(r.get_child("pair"));auto ps=ja(r.get_child("poses"));need(ps.size()==2,"TWO_POSES");std::vector<Pose>vs{anc};for(int z=0;z<2;z++){Pose s=pose(ps[z]);need(s.t>=Q(0)&&s.t<=Q(1)&&fits(s,A,L),"ILLEGAL_WITNESS");need(member(s,groups[p[z]],root),"WITNESS_COMPONENT");for(V x:grid){Q m=-point_margin(s,A,x);need(m>Q(0),"WITNESS_CAPTURES_GRID");minavoid=qmin(minavoid,m);}vs.push_back(s);}for(int i=0;i<3;i++)for(int k=i+1;k<3;k++){Q g=gap(vs[i],A,vs[k],A);need(g>Q(0),"WITNESS_OVERLAP");minsep=qmin(minsep,g);}compat++;}need(compat==128,"COMPATIBLE_COUNT");int unknown=0;for(auto&r:ja(j.get_child("unknown_pairs"))){pairid(r);unknown++;}need(unknown==8&&seen.size()==153,"PAIR_INVENTORY_COMPLETE");
 unsigned matched=0;int blocks=0;for(auto&e:ja(j.get_child("matching"))){auto p=ja(e);need(p.size()==2,"MATCH_SHAPE");int a=std::stoi(p[0].data()),b=std::stoi(p[1].data());need(0<=a&&a<b&&b<18&&((adj[a]>>b)&1)&&!(matched&(1u<<a))&&!(matched&(1u<<b)),"INVALID_MATCHING");matched|=(1u<<a)|(1u<<b);blocks++;}need(blocks==7,"MATCHING_SIZE");std::array<long long,19>counts{},holes{};std::vector<char>valid(1u<<18);valid[0]=1;for(unsigned m=0;m<(1u<<18);m++){if(m){int i=__builtin_ctz(m);unsigned r=m^(1u<<i);valid[m]=valid[r]&&!(r&adj[i]);}if(valid[m]){int k=pop(m);counts[k]++;if(m&&k>=1+int(bool(m&1))+int(bool(m&(1u<<10))))holes[k]++;}}
 auto check=[&](const std::string&k,const auto&c){auto e=ja(j.get_child(k));need(e.size()==19,"COUNT_LENGTH");for(int a=0;a<19;a++)need(std::stoll(e[a].data())==c[a],"GRAPH_COUNT_MISMATCH");};check("expected_counts",counts);check("expected_counts_with_holes",holes);unsigned mx=j.get<unsigned>("max_independent_mask");need(mx<(1u<<18)&&valid[mx]&&pop(mx)==11&&counts[11]==1,"MAX_GRAPH_WITNESS");for(int k=12;k<19;k++)need(counts[k]==0,"GRAPH_UPPER_BOUND");
 auto pp=ja(j.get_child("partial_poses")),ii=ja(j.get_child("partial_components")),hh=ja(j.get_child("partial_halfwidths"));need(pp.size()==9&&ii.size()==9&&hh.size()==3,"PARTIAL_SHAPE");Q ex=qr(hh[0].data()),ey=qr(hh[1].data()),et=qr(hh[2].data());need(ex>Q(0)&&ey>Q(0)&&et>Q(0),"POSITIVE_WIDTH");auto ra=sj.get_child("anchor");need(ex<=getq(ra,"ex")&&ey<=getq(ra,"ey")&&et<=getq(ra,"et")&&anc.t-et>=Q(0)&&anc.t+et<=Q(1),"PARTIAL_ANCHOR_DOMAIN");Q O=A*(Q(1)+Q(2)*et)+Q(2)*(ex+ey);std::vector<Pose>vs{anc};std::set<int>is;Q psep=Q(1000),pavoid=Q(1000);for(int z=0;z<9;z++){int g=std::stoi(ii[z].data());need(0<=g&&g<18&&is.insert(g).second,"PARTIAL_COMPONENT");Pose p=pose(pp[z]);need(p.t-et>=Q(0)&&p.t+et<=Q(1)&&fits(p,O,L)&&member(p,groups[g],root),"PARTIAL_OUTER_ILLEGAL");for(V x:grid){Q a=-point_margin(p,O,x);need(a>Q(0),"PARTIAL_OUTER_CAPTURE");pavoid=qmin(pavoid,a);}vs.push_back(p);}need(fits(anc,O,L),"ANCHOR_OUTER_ILLEGAL");for(int a=0;a<10;a++)for(int b=a+1;b<10;b++){Q g=gap(vs[a],O,vs[b],O);need(g>Q(0),"PARTIAL_OUTER_OVERLAP");psep=qmin(psep,g);}
 std::ostringstream o;o<<"{\"schema\":\"n17.c029.joint-graph-result.v1\",\"status\":\"PASS_FINITE_GRAPH_AND_REAL_WITNESSES\",\"excluded_pairs\":17,\"compatible_triples\":128,\"unknown_pairs\":8,\"pair_nodes\":"<<pairnodes<<",\"hole_nodes\":"<<ownernodes<<",\"avoider_upper\":11,\"partial_avoiders\":9,\"partial_total_squares\":10,\"partial_outer_pair_checks\":45,\"minimum_triple_gap\":"<<quoted(qs(minsep))<<",\"minimum_triple_avoidance\":"<<quoted(qs(minavoid))<<",\"partial_outer_gap\":"<<quoted(qs(psep))<<",\"partial_outer_avoidance\":"<<quoted(qs(pavoid))<<",\"independent_counts\":[";for(int k=0;k<19;k++){if(k)o<<',';o<<counts[k];}o<<"],\"counts_with_holes\":[";for(int k=0;k<19;k++){if(k)o<<',';o<<holes[k];}o<<"],\"no_new_global_lower_bound\":true}";write_new(v[6],o.str());std::cout<<"PASS graph upper=11 partial=9 compatible_triples=128\n";return 0;
}catch(const std::exception&e){std::cerr<<"REJECT "<<e.what()<<'\n';return 1;}}
