'use strict';
// Independent polygon geometry and recursive independent-set enumeration.
const fs=require('fs'),path=require('path');
const {Q,q}=require('../../followup_c021/src/bigq.js');
const {strictParse}=require('../../followup_c028/src/strict_json.js');
const P=Q.parse,need=(v,s)=>{if(!v)throw Error(s);},eq=(a,b)=>a.cmp(b)===0;
const min=(a,b)=>a.cmp(b)<0?a:b,max=(a,b)=>a.cmp(b)>0?a:b;
const add=(a,b)=>[a[0].add(b[0]),a[1].add(b[1])],sub=(a,b)=>[a[0].sub(b[0]),a[1].sub(b[1])],scale=(a,s)=>a.map(x=>x.mul(s));
const dot=(a,b)=>a[0].mul(b[0]).add(a[1].mul(b[1])),cross=(a,b)=>a[0].mul(b[1]).sub(a[1].mul(b[0]));
function pose(j){return {c:[P(j.cx),P(j.cy)],t:P(j.t)};}
function polygon(s,A){let d=q(1).add(s.t.mul(s.t)),u=[q(1).sub(s.t.mul(s.t)).div(d),s.t.mul(2).div(d)],v=[u[1].neg(),u[0]];return [[-1,-1],[1,-1],[1,1],[-1,1]].map(([i,j])=>add(s.c,scale(add(scale(u,i),scale(v,j)),A.div(2))));}
function fits(p,L){return p.every(v=>v.every(x=>x.cmp(0)>=0&&x.cmp(L)<=0));}
function margin(p,A,z){let m=q(1000);for(let i=0;i<4;i++)m=min(m,cross(sub(p[(i+1)%4],p[i]),sub(z,p[i])).div(A));return m;}
function gap(a,A,b,B){let g=q(-1000);for(const [p,S]of[[a,A],[b,B]])for(let i=0;i<2;i++){let e=scale(sub(p[i+1],p[i]),q(1).div(S)),n=[e[1].neg(),e[0]];let x=a.map(v=>dot(n,v)),y=b.map(v=>dot(n,v)),xmin=x.reduce(min),xmax=x.reduce(max),ymin=y.reduce(min),ymax=y.reduce(max);g=max(g,max(ymin.sub(xmax),xmin.sub(ymax)));}return g;}
function member(p,g,root){let vs=[...p.c,p.t],poss=vs.map((v,d)=>{let z=v.sub(root[d][0]).mul(64).div(root[d][1].sub(root[d][0]));if(z.cmp(0)<0||z.cmp(64)>0)return [];let k=Number(z.n/z.d),r=[];if(k<64)r.push(k);if(eq(z,q(k))&&k>0)r.push(k-1);return r;});let keys=new Set(g.cell_keys);for(let x of poss[0])for(let y of poss[1])for(let t of poss[2])if(keys.has((x*64+y)*64+t))return true;return false;}
function main(sj,aj,fj,j,receipts){
 need(j.schema==='n17.c029.joint-graph.v1','SCHEMA');const L=P(sj.L),T=P(sj.cap),A=L.div(T),anc=pose(j.anchor),ref=pose(sj.anchor),ancpoly=polygon(anc,A);
 need(eq(P(aj.cap),T)&&eq(P(aj.parent_side),A),'TARGET_IDENTITY');need(eq(anc.c[0],ref.c[0])&&eq(anc.c[1],ref.c[1])&&eq(anc.t,ref.t),'ANCHOR_IDENTITY');need(fits(ancpoly,L),'ILLEGAL_ANCHOR');
 const alpha=q(1).sub(P(sj.epsilon)),step=T.sub(alpha.mul(2)).div(3),grid=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++)grid.push([A.mul(alpha.add(step.mul(x))),A.mul(alpha.add(step.mul(y)))]);
 let am=0;grid.forEach((p,i)=>{if(margin(ancpoly,A,p).cmp(0)>0)am|=1<<i;});need(am===2,'ANCHOR_POINT_ID');
 need(aj.root.length===3&&aj.root.every(x=>x.length===2),'ROOT_SHAPE');const root=aj.root.map(r=>r.map(P)),groups=fj.components;need(groups.length===18,'COMPONENT_COUNT');for(const g of groups){let r=g.center_rectangle;need(r.length===2&&r.every(x=>x.length===2),'CENTER_RECTANGLE');let w=P(r[0][1]).sub(P(r[0][0])),h=P(r[1][1]).sub(P(r[1][0]));need(w.cmp(0)>0&&h.cmp(0)>0&&w.mul(w).add(h.mul(h)).cmp(A.mul(A))<0,'COMPONENT_CAPACITY');}
 const read=p=>strictParse(fs.readFileSync(p,'utf8')),name=(a,b)=>String(a).padStart(2,'0')+'_'+String(b).padStart(2,'0');let adj=Array(18).fill(0),seen=new Set(),pairnodes=0,ownernodes=0;
 function pairid(r){need(Array.isArray(r)&&r.length===2,'PAIR_SHAPE');let[a,b]=r;need(Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&a<b&&b<18&&!seen.has(a*18+b),'PAIR_RANGE_OR_DUPLICATE');seen.add(a*18+b);return[a,b];}
 for(let e of j.edges){let[a,b]=pairid(e);adj[a]|=1<<b;adj[b]|=1<<a;const r=read(path.join(receipts,'pair_'+name(a,b)+'_bigint.json'));need(r.status==='PASS_CONTINUOUS_PAIR_EXCLUSION'&&JSON.stringify(r.pair)===JSON.stringify([a,b])&&eq(P(r.cap),T),'PAIR_RECEIPT');pairnodes+=r.nodes;}
 need(j.edges.length===17,'EDGE_COUNT');for(let[g,k]of[[0,0],[10,2]]){let r=read(path.join(receipts,'fullowner_'+name(g,k)+'_bigint.json'));need(r.status==='PASS_COMPONENT_FORCES_UNOWNED_POINT'&&r.component===g&&r.point===k&&eq(P(r.cap),T),'HOLE_RECEIPT');ownernodes+=r.nodes;}
 let compat=0,minsep=q(1000),minavoid=q(1000);for(let r of j.compatible_pairs){let ids=pairid(r.pair);need(r.poses.length===2,'TWO_POSES');let polys=[ancpoly];r.poses.forEach((s,z)=>{let p=pose(s),pg=polygon(p,A);need(p.t.cmp(0)>=0&&p.t.cmp(1)<=0&&fits(pg,L),'ILLEGAL_WITNESS');need(member(p,groups[ids[z]],root),'WITNESS_COMPONENT');for(let x of grid){let m=margin(pg,A,x).neg();need(m.cmp(0)>0,'WITNESS_CAPTURES_GRID');minavoid=min(minavoid,m);}polys.push(pg);});for(let i=0;i<3;i++)for(let k=i+1;k<3;k++){let g=gap(polys[i],A,polys[k],A);need(g.cmp(0)>0,'WITNESS_OVERLAP');minsep=min(minsep,g);}compat++;}
 need(compat===128,'COMPATIBLE_COUNT');for(let p of j.unknown_pairs)pairid(p);need(j.unknown_pairs.length===8&&seen.size===153,'PAIR_INVENTORY_COMPLETE');
 let matched=0,blocks=0;for(let e of j.matching){need(e.length===2,'MATCH_SHAPE');let[a,b]=e;need(Number.isInteger(a)&&Number.isInteger(b)&&0<=a&&a<b&&b<18&&(adj[a]&(1<<b))&&!(matched&(1<<a))&&!(matched&(1<<b)),'INVALID_MATCHING');matched|=(1<<a)|(1<<b);blocks++;}need(blocks===7,'MATCHING_SIZE');
 // Unlike C++, visit only independent subsets recursively, not all masks with a DP recurrence.
 const counts=Array(19).fill(0),holes=Array(19).fill(0);let maximizers=[],maxsize=-1;
 function visit(i,mask,k){if(i===18){counts[k]++;if(mask&&k>=1+Number(Boolean(mask&1))+Number(Boolean(mask&(1<<10))))holes[k]++;if(k>maxsize){maxsize=k;maximizers=[mask];}else if(k===maxsize)maximizers.push(mask);return;}visit(i+1,mask,k);if(!(mask&adj[i]))visit(i+1,mask|(1<<i),k+1);}
 visit(0,0,0);for(let[key,c]of[['expected_counts',counts],['expected_counts_with_holes',holes]]){need(j[key].length===19,'COUNT_LENGTH');need(JSON.stringify(j[key])===JSON.stringify(c),'GRAPH_COUNT_MISMATCH');}need(maxsize===11&&maximizers.length===1&&maximizers[0]===j.max_independent_mask,'MAX_GRAPH_WITNESS');
 need(j.partial_poses.length===9&&j.partial_components.length===9&&j.partial_halfwidths.length===3,'PARTIAL_SHAPE');let[ex,ey,et]=j.partial_halfwidths.map(P);need(ex.cmp(0)>0&&ey.cmp(0)>0&&et.cmp(0)>0,'POSITIVE_WIDTH');need(ex.cmp(P(sj.anchor.ex))<=0&&ey.cmp(P(sj.anchor.ey))<=0&&et.cmp(P(sj.anchor.et))<=0&&anc.t.sub(et).cmp(0)>=0&&anc.t.add(et).cmp(1)<=0,'PARTIAL_ANCHOR_DOMAIN');const O=A.mul(q(1).add(et.mul(2))).add(ex.add(ey).mul(2));let polys=[polygon(anc,O)],is=new Set(),psep=q(1000),pavoid=q(1000);
 j.partial_poses.forEach((x,z)=>{let g=j.partial_components[z];need(Number.isInteger(g)&&0<=g&&g<18&&!is.has(g),'PARTIAL_COMPONENT');is.add(g);let p=pose(x),pg=polygon(p,O);need(p.t.sub(et).cmp(0)>=0&&p.t.add(et).cmp(1)<=0&&fits(pg,L)&&member(p,groups[g],root),'PARTIAL_OUTER_ILLEGAL');for(let v of grid){let a=margin(pg,O,v).neg();need(a.cmp(0)>0,'PARTIAL_OUTER_CAPTURE');pavoid=min(pavoid,a);}polys.push(pg);});need(fits(polys[0],L),'ANCHOR_OUTER_ILLEGAL');for(let a=0;a<10;a++)for(let b=a+1;b<10;b++){let g=gap(polys[a],O,polys[b],O);need(g.cmp(0)>0,'PARTIAL_OUTER_OVERLAP');psep=min(psep,g);}
 return {schema:'n17.c029.joint-graph-result.v1',status:'PASS_FINITE_GRAPH_AND_REAL_WITNESSES',excluded_pairs:17,compatible_triples:128,unknown_pairs:8,pair_nodes:pairnodes,hole_nodes:ownernodes,avoider_upper:11,partial_avoiders:9,partial_total_squares:10,partial_outer_pair_checks:45,minimum_triple_gap:String(minsep),minimum_triple_avoidance:String(minavoid),partial_outer_gap:String(psep),partial_outer_avoidance:String(pavoid),independent_counts:counts,counts_with_holes:holes,no_new_global_lower_bound:true};
}
if(require.main===module)try{need(process.argv.length===8,'USAGE_SPEC_ATLAS_FRONTIER_GRAPH_RECEIPTS_OUTPUT');let[sp,ap,fp,gp,rp,op]=process.argv.slice(2);need(!fs.existsSync(op),'FRESH_OUTPUT_REQUIRED');let read=p=>strictParse(fs.readFileSync(p,'utf8'));let out=main(read(sp),read(ap),read(fp),read(gp),rp);fs.writeFileSync(op,JSON.stringify(out)+'\n',{flag:'wx'});console.log('PASS graph upper=11 partial=9 compatible_triples=128');}catch(e){console.error('REJECT '+e.message);process.exit(1);}
module.exports={main};
