'use strict';
const fs=require('fs'),{Q,q}=require('../../followup_c021/src/bigq.js'),{strictParse}=require('../../followup_c028/src/strict_json.js'),old=require('../../followup_c028/src/atlas.js'),{overlap}=require('./pair_verify.js');
const need=(v,m)=>{if(!v)throw Error(m);},P=Q.parse,lt=(a,b)=>a.cmp(b)<0,eq=(a,b)=>a.cmp(b)===0,min=(a,b)=>lt(a,b)?a:b,max=(a,b)=>lt(a,b)?b:a;
function missed(b,p,A,face){if(face<0||face>3)return false;const r=A.div(2);for(let i=0;i<2;i++)for(let j=0;j<2;j++){let x=p[0].sub(b[0][i]),y=p[1].sub(b[1][j]);let abc=[[x.neg().sub(r),y.mul(2),x.sub(r)],[x.sub(r),y.mul(-2),x.neg().sub(r)],[y.neg().sub(r),x.mul(-2),y.sub(r)],[y.sub(r),x.mul(2),y.neg().sub(r)]][face];if(!old.quadraticPositive(...abc,...b[2]))return false;}return true;}
function main(sj,fj,j,id,text){const s=old.readSpec(sj);need(j.schema==='n17.c029.component-forced-hole.v1','SCHEMA');let rows=j.cases.filter(r=>r.id===id);need(rows.length===1,'CASE_ID');const rec=rows[0],g=rec.component,k=rec.point;need(Number.isInteger(g)&&Number.isInteger(k)&&g>=0&&g<18&&k>=0&&k<16&&k!==sj.anchor_point_index,'CASE_RANGE');need(fj.components.length===18,'COMPONENT_COUNT');let gr=fj.components[g];need(gr.id===g&&gr.index_lo.length===3&&gr.index_hi.length===3,'COMPONENT_ID');let a=s.root.map((r,d)=>{let l=gr.index_lo[d],h=gr.index_hi[d];need(Number.isInteger(l)&&Number.isInteger(h)&&0<=l&&l<=h&&h<64,'COMPONENT_INDEX');let w=r[1].sub(r[0]);return[r[0].add(w.mul(l).div(64)),r[0].add(w.mul(h+1).div(64))];});need(rec.root.length===3&&rec.root.every(x=>x.length===2),'BOX_DIMENSION');let b=rec.root.map(d=>d.map(P));need(b.every(x=>lt(x[0],x[1])),'BOX_ORDER');let p=s.grid[k];for(let d=0;d<2;d++)need(eq(b[d][0],max(s.half,p[d].sub(s.A.mul(3).div(4))))&&eq(b[d][1],min(s.L.sub(s.half),p[d].add(s.A.mul(3).div(4)))),'OWNER_ROOT_COVERAGE');need(eq(b[2][0],q(0))&&eq(b[2][1],q(1)),'OWNER_ALL_ANGLES');let anc=[['cx','ex'],['cy','ey'],['t','et']].map(([c,w])=>[P(sj.anchor[c]).sub(P(sj.anchor[w])),P(sj.anchor[c]).add(P(sj.anchor[w]))]);let tokens=text.trim().split(/\s+/),at=0;need(tokens[at++]==='C029_AVOID_OWNER_V1','TREE_HEADER');let st={nodes:0,split:0,overlap:0,wall:0,grid:0,required_point_miss:0,anchor:0,max_depth:0};
 function visit(a,b,dep){need(dep<=80,'DEPTH_LIMIT');need(++st.nodes<=5000000,'NODE_LIMIT');st.max_depth=Math.max(st.max_depth,dep);need(at<tokens.length,'TREE_TRUNCATED');let op=tokens[at++];if(op==='X'){need(overlap(a,b,s.A),'UNPROVED_PAIR_OVERLAP');st.overlap++;return;}need(at+1<tokens.length&&/^\d+$/.test(tokens[at])&&/^\d+$/.test(tokens[at+1]),'TREE_INDEX');let side=Number(tokens[at++]),d=Number(tokens[at++]);need(side===0||side===1,'SIDE_INDEX');let v=side?b:a;
 if(op==='S'){need(d>=0&&d<3,'SPLIT_INDEX');st.split++;let m=v[d][0].add(v[d][1]).div(2),aa=a.map(x=>x.slice()),bb=b.map(x=>x.slice());(side?bb:aa)[d][1]=m;visit(aa,bb,dep+1);aa=a.map(x=>x.slice());bb=b.map(x=>x.slice());(side?bb:aa)[d][0]=m;visit(aa,bb,dep+1);}
 else if(op==='W'){need(d>=0&&d<4&&old.wall(s,v,d),'UNPROVED_WALL');st.wall++;}
 else if(op==='P'){need(side===0&&d>=0&&d<16&&old.captured(s,v,d),'UNPROVED_AVOIDER_GRID_CAPTURE');st.grid++;}
 else if(op==='N'){need(side===1&&missed(v,p,s.A,d),'UNPROVED_REQUIRED_POINT_MISS');st.required_point_miss++;}
 else if(op==='A'){need(d===0&&overlap(anc,v,s.A),'UNPROVED_ANCHOR_OVERLAP');st.anchor++;}
 else throw Error('UNKNOWN_OPCODE');}
 visit(a,b,0);need(at===tokens.length,'TREE_EXTRA');need(st.nodes===2*st.split+1&&st.split+1===st.overlap+st.wall+st.grid+st.required_point_miss+st.anchor,'TREE_COMPLETENESS');return{schema:'n17.c029.forced-hole-proof.v1',id,component:g,point:k,nodes:st.nodes,split:st.split,overlap:st.overlap,wall:st.wall,grid:st.grid,required_point_miss:st.required_point_miss,anchor:st.anchor,max_depth:st.max_depth,cap:String(s.T),status:'PASS_COMPONENT_FORCES_UNOWNED_POINT'};
}
if(require.main===module)try{need(process.argv.length===8,'USAGE_SPEC_FRONTIER_CASES_ID_TREE_OUTPUT');let[sp,fp,jp,id,tp,op]=process.argv.slice(2);need(!fs.existsSync(op),'FRESH_OUTPUT_REQUIRED');let read=p=>strictParse(fs.readFileSync(p,'utf8')),out=main(read(sp),read(fp),read(jp),id,fs.readFileSync(tp,'utf8'));fs.writeFileSync(op,JSON.stringify(out)+'\n',{flag:'wx'});console.log('PASS '+id+' nodes='+out.nodes);}catch(e){console.error('REJECT '+e.message);process.exit(1);}
module.exports={main,missed};
