'use strict';
// Exact quadratic-positivity checker; does not use C++ angle extrema.
const fs=require('fs');const {Q,q}=require('../../followup_c021/src/bigq.js');const {strictParse}=require('../../followup_c028/src/strict_json.js');const old=require('../../followup_c028/src/atlas.js');
const need=(x,m)=>{if(!x)throw Error(m);};const P=Q.parse,lt=(a,b)=>a.cmp(b)<0,eq=(a,b)=>a.cmp(b)===0,min=(a,b)=>lt(a,b)?a:b;
const dot=(a,b)=>a[0].mul(b[0]).add(a[1].mul(b[1])),cr=(a,b)=>a[0].mul(b[1]).sub(a[1].mul(b[0]));
function frame(t){let d=q(1).add(t.mul(t));return[q(1).sub(t.mul(t)).div(d),t.mul(2).div(d)];}
function overlap(a,b,A){let rel=q(1);if(lt(a[2][1],b[2][0])||lt(b[2][1],a[2][0])){const x0=frame(a[2][0]),x1=frame(a[2][1]),y0=frame(b[2][0]),y1=frame(b[2][1]);rel=min(dot(x1,y0).add(cr(x1,y0).abs()),dot(x0,y1).add(cr(x0,y1).abs()));}const r=A.mul(q(1).add(rel)).div(2),d=[b[0][0].sub(a[0][1]),b[0][1].sub(a[0][0]),b[1][0].sub(a[1][1]),b[1][1].sub(a[1][0])];return old.projectionsBelow(...d,...a[2],r)&&old.projectionsBelow(...d,...b[2],r);}
function box(x){need(Array.isArray(x)&&x.length===3,'BOX_DIMENSION');let b=x.map(p=>{need(Array.isArray(p)&&p.length===2,'BOX_INTERVAL');let a=p.map(P);need(lt(a[0],a[1]),'BOX_ORDER');return a;});need(b[2][0].cmp(q(0))>=0&&b[2][1].cmp(q(1))<=0,'ANGLE_CHART');return b;}
function main(sj,fj,j,pair,text){let s=old.readSpec(sj);need(j.schema==='n17.c029.component-pairs.v1','SCHEMA');need(eq(P(j.L),s.L)&&eq(P(j.cap),s.T)&&eq(P(j.A),s.A),'TARGET_IDENTITY');let anc=box(j.anchor),raw=sj.anchor;for(let d=0;d<3;d++){let c=P(raw[['cx','cy','t'][d]]),w=P(raw[['ex','ey','et'][d]]);need(eq(anc[d][0],c.sub(w))&&eq(anc[d][1],c.add(w)),'ANCHOR_IDENTITY');}need(j.grid.length===16,'GRID_SIZE');j.grid.forEach((p,k)=>need(p.length===2&&eq(P(p[0]),s.grid[k][0])&&eq(P(p[1]),s.grid[k][1]),'GRID_IDENTITY'));
 need(j.roots.length===18&&fj.components.length===18,'COMPONENT_COUNT');let boxes=j.roots.map((r,n)=>{let b=box(r),g=fj.components[n];need(g.id===n&&g.index_lo.length===3&&g.index_hi.length===3,'COMPONENT_ID');for(let d=0;d<3;d++){let l=g.index_lo[d],h=g.index_hi[d];need(Number.isInteger(l)&&Number.isInteger(h)&&0<=l&&l<=h&&h<64,'COMPONENT_INDEX');let w=s.root[d][1].sub(s.root[d][0]);need(eq(b[d][0],s.root[d][0].add(w.mul(l).div(64)))&&eq(b[d][1],s.root[d][0].add(w.mul(h+1).div(64))),'COMPONENT_ROOT');}return b;});need(/^\d+,\d+$/.test(pair),'PAIR_ID');let [i,k]=pair.split(',').map(Number);need(0<=i&&i<k&&k<18,'PAIR_RANGE');let tokens=text.trim().split(/\s+/),at=0;need(tokens[at++]==='C029_PAIR_V1','TREE_HEADER');let st={nodes:0,split:0,overlap:0,wall:0,grid:0,anchor:0,max_depth:0};
 function visit(a,b,dep){need(dep<=80,'DEPTH_LIMIT');need(++st.nodes<=5000000,'NODE_LIMIT');st.max_depth=Math.max(dep,st.max_depth);need(at<tokens.length,'TREE_TRUNCATED');let op=tokens[at++];if(op==='X'){need(overlap(a,b,s.A),'UNPROVED_PAIR_OVERLAP');st.overlap++;return;}need(at+1<tokens.length&&/^\d+$/.test(tokens[at])&&/^\d+$/.test(tokens[at+1]),'TREE_INDEX');let side=Number(tokens[at++]),d=Number(tokens[at++]);need(side===0||side===1,'SIDE_INDEX');let v=side?b:a;
 if(op==='S'){need(d>=0&&d<3,'SPLIT_INDEX');st.split++;let m=v[d][0].add(v[d][1]).div(2),aa=a.map(x=>x.slice()),bb=b.map(x=>x.slice());(side?bb:aa)[d][1]=m;visit(aa,bb,dep+1);aa=a.map(x=>x.slice());bb=b.map(x=>x.slice());(side?bb:aa)[d][0]=m;visit(aa,bb,dep+1);}
 else if(op==='W'){need(d>=0&&d<4&&old.wall(s,v,d),'UNPROVED_WALL');st.wall++;}
 else if(op==='P'){need(d>=0&&d<16&&old.captured(s,v,d),'UNPROVED_GRID_CAPTURE');st.grid++;}
 else if(op==='A'){need(d===0&&overlap(anc,v,s.A),'UNPROVED_ANCHOR_OVERLAP');st.anchor++;}
 else throw Error('UNKNOWN_OPCODE');}
 visit(boxes[i],boxes[k],0);need(at===tokens.length,'TREE_EXTRA');need(st.nodes===2*st.split+1&&st.split+1===st.overlap+st.wall+st.grid+st.anchor,'TREE_COMPLETENESS');return{schema:'n17.c029.pair-proof.v1',pair:[i,k],nodes:st.nodes,split:st.split,overlap:st.overlap,wall:st.wall,grid:st.grid,anchor:st.anchor,max_depth:st.max_depth,cap:String(s.T),status:'PASS_CONTINUOUS_PAIR_EXCLUSION'};
}
if(require.main===module)try{need(process.argv.length===8,'USAGE_SPEC_FRONTIER_INPUT_PAIR_TREE_OUTPUT');let [sp,fp,ip,pair,tp,op]=process.argv.slice(2);need(!fs.existsSync(op),'FRESH_OUTPUT_REQUIRED');const read=p=>strictParse(fs.readFileSync(p,'utf8'));let out=main(read(sp),read(fp),read(ip),pair,fs.readFileSync(tp,'utf8'));fs.writeFileSync(op,JSON.stringify(out)+'\n',{flag:'wx'});console.log('PASS pair='+pair+' nodes='+out.nodes);}catch(e){console.error('REJECT '+e.message);process.exit(1);}
module.exports={main,overlap};
