'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const need=(v,s)=>{if(!v)throw Error(s);},sha=b=>crypto.createHash('sha256').update(b).digest('hex'),clone=x=>JSON.parse(JSON.stringify(x));
function main(root,bin,result,out){
 need(!fs.existsSync(out),'FRESH_CONTROL_DIRECTORY_REQUIRED');fs.mkdirSync(out,{recursive:true});const rel='project/followup_c028',data=path.join(root,rel,'data'),src=path.join(root,rel,'src');
 const base={stabbing:JSON.parse(fs.readFileSync(path.join(data,'stabbing.json'))),spec:JSON.parse(fs.readFileSync(path.join(data,'atlas.json'))),atlas:JSON.parse(fs.readFileSync(path.join(result,'atlas_cpp.json'))),witness:JSON.parse(fs.readFileSync(path.join(data,'frontier_witnesses.json'))),finite:JSON.parse(fs.readFileSync(path.join(root,'project/followup_c026/data/finite_comparison.json'))),pred:JSON.parse(fs.readFileSync(path.join(data,'predicates.json')))};
 const tree=fs.readFileSync(path.join(data,'atlas.tree'),'utf8'),cases=[];
 const neg=(id,kind,reason,fn)=>cases.push({id,kind,reason,positive:false,fn});const pos=(id,kind,fn)=>cases.push({id,kind,positive:true,fn});
 neg('stabbing_schema','stabbing','SCHEMA',x=>x.stabbing.schema='bad');
 neg('stabbing_dimensions','stabbing','GRID_CARDINALITY',x=>x.stabbing.grid_order=5);
 neg('zero_epsilon','stabbing','STRICT_ENDPOINT_AND_SPACING',x=>x.stabbing.endpoint_epsilon='0/1');
 neg('too_large_angle','stabbing','NEAR_GRID_GAP',x=>x.stabbing.targets[0].near_t='1/4');
 neg('angle_order','stabbing','PARAMETER_DOMAIN',x=>x.stabbing.targets[0].two_t=x.stabbing.targets[0].near_t);
 neg('zero_spacing_loss','stabbing','STRICT_ENDPOINT_AND_SPACING',x=>x.stabbing.spacing_loss='0/1');
 neg('seed_count','stabbing','INPUT_COUNT',x=>x.stabbing.seeds.pop());
 neg('zero_seed_width','stabbing','SEED_DOMAIN',x=>x.stabbing.seeds[0].et='0/1');
 neg('seed_overlaps_near_angles','stabbing','SEED_DOMAIN',x=>x.stabbing.seeds[0].t='1/100');
 neg('bad_seed_location','stabbing','BOX_WITHOUT_COMMON_GRID_POINT',x=>x.stabbing.seeds[0].cx='100/1');
 neg('atlas_schema','atlas','SCHEMA',x=>x.spec.schema='bad');
 neg('atlas_grid_gap','atlas','GRID_GAP',x=>x.spec.near_t='1/4');
 neg('atlas_zero_endpoint_margin','atlas','ENDPOINT_STRICTNESS',x=>x.spec.epsilon='0/1');
 neg('atlas_zero_anchor_width','atlas','POSITIVE_ANCHOR_WIDTH',x=>x.spec.anchor.ex='0/1');
 neg('atlas_anchor_index','atlas','ANCHOR_POINT_INDEX',x=>x.spec.anchor_point_index=16);
 neg('atlas_wrong_anchor_point','atlas','ANCHOR_GRID_CAPTURE',x=>x.spec.anchor_point_index=15);
 neg('atlas_depth_overflow','atlas','DEPTH_RANGE',x=>x.spec.max_depth=22);
 neg('atlas_bad_header','atlas','TREE_HEADER',x=>x.tree='BROKEN\n');
 neg('atlas_missing_root','atlas','TREE_TRUNCATED',x=>x.tree='C028_ATLAS_V2\n');
 neg('atlas_invalid_split','atlas','INVALID_SPLIT',x=>x.tree='C028_ATLAS_V2\nS 3\n');
 neg('atlas_wrong_schedule','atlas','SPLIT_SCHEDULE',x=>x.tree='C028_ATLAS_V2\nS 1\n');
 neg('atlas_unproved_wall','atlas','UNPROVED_WALL_LEAF',x=>x.tree='C028_ATLAS_V2\nW 0\n');
 neg('atlas_unproved_point','atlas','UNPROVED_POINT_LEAF',x=>x.tree='C028_ATLAS_V2\nP 0\n');
 neg('atlas_unproved_corner','atlas','UNPROVED_CORNER_LEAF',x=>x.tree='C028_ATLAS_V2\nC 0\n');
 neg('atlas_unproved_disk','atlas','UNPROVED_ANCHOR_LEAF',x=>x.tree='C028_ATLAS_V2\nA\n');
 neg('atlas_unproved_kernel','atlas','UNPROVED_KERNEL_LEAF',x=>x.tree='C028_ATLAS_V2\nK\n');
 neg('atlas_unproved_joint','atlas','UNPROVED_JOINT_LEAF',x=>x.tree='C028_ATLAS_V2\nJ\n');
 neg('atlas_early_frontier','atlas','PREMATURE_FRONTIER',x=>x.tree='C028_ATLAS_V2\nU\n');
 neg('atlas_unknown_opcode','atlas','UNKNOWN_LEAF_OPCODE',x=>x.tree='C028_ATLAS_V2\nZ\n');
 neg('atlas_trailing_tokens','atlas','TREE_EXTRA_TOKENS',x=>{x.spec.max_depth=0;x.tree='C028_ATLAS_V2\nU U\n';});
 neg('frontier_target','frontier','TARGET_IDENTITY',x=>x.atlas.cap='467/100');
 neg('frontier_root','frontier','ROOT_IDENTITY',x=>x.atlas.root[0][0]='0/1');
 neg('frontier_duplicate','frontier','DUPLICATE_FRONTIER_CELL',x=>x.atlas.frontier_paths.push(x.atlas.frontier_paths[0]));
 neg('frontier_count','frontier','FRONTIER_COUNT',x=>x.atlas.frontier_paths.pop());
 neg('frontier_bad_bits','frontier','FRONTIER_PATH_BITS',x=>x.atlas.frontier_paths[0]='X'+x.atlas.frontier_paths[0].slice(1));
 neg('frontier_bad_witness','frontier','ILLEGAL_WITNESS',x=>x.witness.witnesses[0].pose.cx='100/1');
 neg('frontier_overlap','frontier','WITNESS_OVERLAP',x=>x.witness.witnesses[0].pose=clone(x.witness.anchor));
 neg('frontier_missing_path','frontier','WITNESS_NOT_IN_FRONTIER',x=>x.witness.witnesses[0].frontier_path='0'.repeat(18));
 neg('frontier_wide_box','frontier','BOX_WALL',x=>x.witness.witnesses[0].halfwidths=['1/1','1/1','1/1000']);
 neg('frontier_required_control','frontier','BOUNDARY_CONTROL_REQUIRED',x=>x.witness.open_boundary_control=false);
 neg('frontier_zero_scale','frontier','SCALE',x=>x.finite.scale='0');
 neg('frontier_dual_negative','frontier','DUAL_ENTRY',x=>x.finite.models.find(m=>m.id==='full_40_point_basis').dual[0].units='-1');
 neg('frontier_dual_sum','frontier','RETAINED_DUAL_SUM',x=>x.finite.models.find(m=>m.id==='full_40_point_basis').expected_dual_sum='1');
 neg('frontier_oversized_component','frontier','COMPONENT_NOT_CAPACITY_ONE',x=>{x.atlas.frontier_paths=[];for(let a=0;a<64;a++){const bits=a.toString(2).padStart(6,'0');x.atlas.frontier_paths.push([...bits].map(b=>b+'00').join(''));}x.atlas.counts.unresolved=64;});
 neg('quadratic_interior_false_positive','predicates','PREDICATE_EXPECTATION',x=>x.pred.cases[0].expected=true);
 neg('quadratic_strict_equality','predicates','PREDICATE_EXPECTATION',x=>x.pred.cases[2].expected=true);
 neg('quadratic_reversed_interval','predicates','PREDICATE_DOMAIN',x=>x.pred.cases[0].t=['1/1','0/1']);
 neg('quadratic_zero_bound','predicates','PREDICATE_DOMAIN',x=>x.pred.cases[0].bound='0/1');
 pos('smaller_near_angles','stabbing',x=>{for(const t of x.stabbing.targets){const[a,b]=t.near_t.split('/');t.near_t=a+'/'+(2n*BigInt(b));}});
 pos('narrower_seed_boxes','stabbing',x=>{for(const s of x.stabbing.seeds){s.ex='1/100';s.ey='1/100';s.et='1/200';}});
 pos('valid_coarse_outer_cover','atlas',x=>{x.spec.max_depth=0;x.tree='C028_ATLAS_V2\nU\n';});
 pos('equivalent_projection_scale','predicates',x=>{for(const c of x.pred.cases){for(const k of['dx','dy'])c[k]=c[k].map(s=>{const[a,b]=s.split('/');return(2n*BigInt(a))+'/'+b;});const[a,b]=c.bound.split('/');c.bound=(2n*BigInt(a))+'/'+b;}});
 pos('fewer_compatible_witnesses','frontier',x=>x.witness.witnesses=x.witness.witnesses.slice(0,3));
 pos('equivalent_large_integer_dual_scale','frontier',x=>{const f=10n**50n;x.finite.scale=String(BigInt(x.finite.scale)*f);for(const m of x.finite.models){m.expected_dual_sum=String(BigInt(m.expected_dual_sum)*f);for(const d of m.dual)d.units=String(BigInt(d.units)*f);}});
 const records=[];for(const c of cases){const x=clone(base);x.tree=tree;c.fn(x);const dir=path.join(out,c.id);fs.mkdirSync(dir);const inputs={};function put(key,value,ext='json'){const p=path.join(dir,key+'.'+ext),b=ext==='json'?JSON.stringify(value)+'\n':value;fs.writeFileSync(p,b);inputs[key]={path:p,sha256:sha(Buffer.from(b)),bytes:Buffer.byteLength(b)};return p;}
 let args=[];if(c.kind==='stabbing')args=[put('stabbing',x.stabbing)];else if(c.kind==='atlas')args=[put('spec',x.spec),put('tree',x.tree,'tree')];else if(c.kind==='predicates')args=[put('pred',x.pred)];else args=[put('spec',x.spec),put('atlas',x.atlas),put('witness',x.witness),put('finite',x.finite)];
 for(const impl of['cpp','bigint']){const output=path.join(dir,impl+'.json');let command,argv;if(impl==='cpp'){command=path.join(bin,c.kind+(process.platform==='win32'?'.exe':''));argv=c.kind==='atlas'?['verify',args[0],'v2',args[1],output]:[...args,output];}else{command=process.execPath;argv=[path.join(src,c.kind+'.js'),...args,output];}const r=cp.spawnSync(command,argv,{encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024});fs.writeFileSync(path.join(dir,impl+'.stdout'),r.stdout||'');fs.writeFileSync(path.join(dir,impl+'.stderr'),r.stderr||'');const ok=!r.error&&!r.signal&&(c.positive?r.status===0:r.status===1&&(r.stderr||'').includes('REJECT '+c.reason));const rec={case:c.id,implementation:impl,positive:c.positive,expected_reason:c.reason||null,passed:ok,command:[command,...argv],inputs:Object.values(inputs),exit:r.status,signal:r.signal,error:r.error?String(r.error):null,stdout:r.stdout,stderr:r.stderr,output_sha256:fs.existsSync(output)?sha(fs.readFileSync(output)):null};records.push(rec);fs.writeFileSync(path.join(out,'PROGRESS.json'),JSON.stringify(records,null,2)+'\n');need(ok,'CONTROL_FAILED '+c.id+' '+impl+' '+r.stderr);}}
 const summary={schema:'n17.c028.controls.v1',status:'PASS_C028_DIRECT_MATHEMATICAL_CONTROLS',negative_executions:records.filter(x=>!x.positive).length,positive_executions:records.filter(x=>x.positive).length,scope:'Inputs are deterministically regenerated by this script; full input hashes and actual process records retained.',records};fs.writeFileSync(path.join(out,'CONTROLS.json'),JSON.stringify(summary,null,2)+'\n');return summary;
}
if(require.main===module)try{need(process.argv.length===6,'USAGE_ROOT_BIN_RESULTS_FRESH_OUTPUT');const r=main(...process.argv.slice(2).map(x=>path.resolve(x)));console.log(r.status+' negative='+r.negative_executions+' positive='+r.positive_executions);}catch(e){console.error('REJECT '+e.message);process.exit(1);}
module.exports={main};
