'use strict';
// Disjoint-set clustering and independent vertex geometry.
const fs=require('fs'),{Q,q}=require('../../followup_c021/src/bigq.js'),{strictParse}=require('./strict_json.js');
const P=Q.parse,need=(v,s)=>{if(!v)throw Error(s);},lt=(a,b)=>a.cmp(b)<0,le=(a,b)=>a.cmp(b)<=0,eq=(a,b)=>a.cmp(b)===0,min=(a,b)=>lt(a,b)?a:b,max=(a,b)=>lt(a,b)?b:a;
const sub=(a,b)=>a.map((x,i)=>x.sub(b[i])),dot=(a,b)=>a[0].mul(b[0]).add(a[1].mul(b[1])),cross=(a,b)=>a[0].mul(b[1]).sub(a[1].mul(b[0]));
function pose(j,ret=false){const p=s=>ret?P(s.includes('/')?s:s+'/1'):P(s);return{C:[p(j.cx),p(j.cy)],t:p(j.t)};}
function verts(p,A){const t=p.t,d=q(1).add(t.mul(t)),c=q(1).sub(t.mul(t)).div(d),s=t.mul(2).div(d),h=A.div(2);return[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>[p.C[0].add(h.mul(c.mul(a).sub(s.mul(b)))),p.C[1].add(h.mul(s.mul(a).add(c.mul(b))))]);}
function pm(poly,A,z){return poly.map((a,i)=>cross(sub(poly[(i+1)%4],a),sub(z,a)).div(A)).reduce(min);}
function fit(poly,L){return poly.every(p=>p.every(x=>le(q(0),x)&&le(x,L)));}
function sep(poly,A,other,B){let best=q(-1000000);for(const[p,size]of[[poly,A],[other,B]])for(let i=0;i<4;i++){const e=sub(p[(i+1)%4],p[i]),n=[e[1].neg().div(size),e[0].div(size)],va=poly.map(p=>dot(p,n)),vb=other.map(p=>dot(p,n));best=max(best,max(vb.reduce(min).sub(va.reduce(max)),va.reduce(min).sub(vb.reduce(max))));}return best;}
function main(sj,aj,wj,fj){
 need(sj.schema==='n17.c028.second-anchor-atlas.v2'&&aj.schema==='n17.c028.atlas-result.v2','ATLAS_SCHEMA');need(wj.schema==='n17.c028.frontier-witnesses.v1','WITNESS_SCHEMA');const L=P(sj.L),T=P(sj.cap),A=L.div(T);need(eq(P(aj.cap),T)&&eq(P(aj.parent_side),A),'TARGET_IDENTITY');const depth=aj.max_depth;need(depth===sj.max_depth&&Number.isInteger(depth)&&depth>=3&&depth<=21&&depth%3===0,'BALANCED_GRID_DEPTH');const N=2**(depth/3);need(Array.isArray(aj.root)&&aj.root.length===3,'ROOT_SHAPE');const root=aj.root.map(a=>{need(a.length===2,'ROOT_SHAPE');const p=a.map(P);need(lt(p[0],p[1]),'ROOT_ORDER');return p;});const nt=P(sj.near_t);need(eq(root[0][0],A.div(2))&&eq(root[1][0],A.div(2))&&eq(root[0][1],L.sub(A.div(2)))&&eq(root[1][1],L.sub(A.div(2)))&&eq(root[2][0],nt)&&eq(root[2][1],q(1).sub(nt).div(q(1).add(nt))),'ROOT_IDENTITY');
 const encode=c=>(c[0]*N+c[1])*N+c[2],coords=k=>[Math.floor(k/(N*N)),Math.floor(k/N)%N,k%N],paths=new Map(),cells=new Set();for(const p of aj.frontier_paths){need(typeof p==='string'&&p.length===depth,'FRONTIER_PATH_LENGTH');const c=[0,0,0];for(let i=0;i<depth;i++){need(p[i]==='0'||p[i]==='1','FRONTIER_PATH_BITS');c[i%3]=2*c[i%3]+Number(p[i]);}const k=encode(c);need(!cells.has(k)&&!paths.has(p),'DUPLICATE_FRONTIER_CELL');cells.add(k);paths.set(p,k);}need(cells.size>0&&cells.size===aj.counts.unresolved,'FRONTIER_COUNT');
 const keys=[...cells].sort((a,b)=>a-b),index=new Map(keys.map((k,i)=>[k,i])),parent=keys.map((_,i)=>i);function find(i){while(parent[i]!==i){parent[i]=parent[parent[i]];i=parent[i];}return i;}function union(i,j){i=find(i);j=find(j);if(i!==j)parent[Math.max(i,j)]=Math.min(i,j);}
 for(let i=0;i<keys.length;i++){const c=coords(keys[i]);for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)for(let t=-1;t<=1;t++){const v=[c[0]+a,c[1]+b,c[2]+t];if(v.some(x=>x<0||x>=N))continue;const k=encode(v),j=index.get(k);if(j!==undefined&&j<i)union(i,j);}}
 const gm=new Map();for(let i=0;i<keys.length;i++){const f=find(i);if(!gm.has(f))gm.set(f,[]);gm.get(f).push(keys[i]);}const groups=[...gm.values()].sort((a,b)=>a[0]-b[0]).map((keys,id)=>{const cc=keys.map(coords),lo=[0,1,2].map(d=>Math.min(...cc.map(x=>x[d]))),hi=[0,1,2].map(d=>Math.max(...cc.map(x=>x[d]))),pad=A.div(1000000),rect=[0,1].map(d=>[root[d][0].add(root[d][1].sub(root[d][0]).mul(lo[d]).div(N)).sub(pad),root[d][0].add(root[d][1].sub(root[d][0]).mul(hi[d]+1).div(N)).add(pad)]),dx=rect[0][1].sub(rect[0][0]),dy=rect[1][1].sub(rect[1][0]),gap=A.mul(A).sub(dx.mul(dx)).sub(dy.mul(dy));need(lt(q(0),gap),'COMPONENT_NOT_CAPACITY_ONE');return{id,keys,lo,hi,rect,gap,witnesses:0};});const owner=new Map();for(const g of groups)for(const k of g.keys)owner.set(k,g.id);
 const anc=pose(wj.anchor),ap=verts(anc,A);need(fit(ap,L),'ILLEGAL_ANCHOR');const ra=pose(sj.anchor);need(le(anc.C[0].sub(ra.C[0]).abs(),P(sj.anchor.ex))&&le(anc.C[1].sub(ra.C[1]).abs(),P(sj.anchor.ey))&&le(anc.t.sub(ra.t).abs(),P(sj.anchor.et)),'ANCHOR_OUTSIDE_RAW_BOX');const alpha=q(1).sub(P(sj.epsilon)),step=T.sub(alpha.mul(2)).div(3),grid=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++)grid.push([A.mul(alpha.add(step.mul(x))),A.mul(alpha.add(step.mul(y)))]);
 const records=[],names=new Set();for(const w of wj.witnesses){const id=w.id,path=w.frontier_path;need(!names.has(id),'DUPLICATE_WITNESS');names.add(id);need(paths.has(path),'WITNESS_NOT_IN_FRONTIER');const p=pose(w.pose),poly=verts(p,A);need(le(q(0),p.t)&&le(p.t,q(1))&&fit(poly,L),'ILLEGAL_WITNESS');const separation=sep(poly,A,ap,A);need(lt(q(0),separation),'WITNESS_OVERLAP');const c=coords(paths.get(path)),pv=[...p.C,p.t];for(let d=0;d<3;d++){const lo=root[d][0].add(root[d][1].sub(root[d][0]).mul(c[d]).div(N)),hi=root[d][0].add(root[d][1].sub(root[d][0]).mul(c[d]+1).div(N));need(le(lo,pv[d])&&le(pv[d],hi),'WITNESS_OUTSIDE_CELL');}
 const av=grid.map(z=>pm(poly,A,z).neg());need(av.every(x=>lt(q(0),x)),'WITNESS_CAPTURES_GRID');need(w.halfwidths.length===3,'BOX_WIDTH_DIMENSION');const[ex,ey,et]=w.halfwidths.map(P);need(lt(q(0),ex)&&lt(q(0),ey)&&lt(q(0),et)&&le(q(0),p.t.sub(et))&&le(p.t.add(et),q(1)),'BOX_WIDTH_RANGE');const out=A.mul(q(1).add(et.mul(2))).add(ex.add(ey).mul(2)),vp=verts(p,out);need(fit(vp,L),'BOX_WALL');const outgap=sep(vp,out,ap,A);need(lt(q(0),outgap),'BOX_OVERLAP');const ov=grid.map(z=>pm(vp,out,z).neg());need(ov.every(x=>lt(q(0),x)),'BOX_CAPTURES_GRID');const g=owner.get(paths.get(path));groups[g].witnesses++;records.push({id,component:g,path,separation_margin:String(separation),grid_avoidance_margin:String(av.reduce(min)),outer_side:String(out),outer_separation_margin:String(outgap),outer_grid_avoidance_margin:String(ov.reduce(min))});}
 need(wj.open_boundary_control===true,'BOUNDARY_CONTROL_REQUIRED');const corner=verts({C:[A.div(2),A.div(2)],t:q(0)},A),oldstep=T.sub(2).div(3);let open=0,closed=0;for(let y=0;y<4;y++)for(let x=0;x<4;x++){const m=pm(corner,A,[A.mul(q(1).add(oldstep.mul(x))),A.mul(q(1).add(oldstep.mul(y)))]);if(lt(q(0),m))open++;if(le(q(0),m))closed++;}need(open===0&&closed===1,'OPEN_BOUNDARY_CONTROL');
 const rq=s=>P(s.includes('/')?s:s+'/1');need(fj.schema==='n17.c026.exact-finite-comparison.v1'&&eq(rq(fj.target),T),'RETAINED_DUAL_INPUT');const D=BigInt(fj.scale);need(D>0n,'SCALE');const diagnostics=[];for(const m of fj.models){if(!['full_40_point_basis','matched_segment_cliques'].includes(m.id))continue;const loads=Array(groups.length).fill(0n),seen=new Set();let sum=0n;for(const e of m.dual){const i=e.row,weight=BigInt(e.units);need(Number.isInteger(i)&&i>=0&&i<fj.poses.length&&i<m.training_count&&weight>0n&&!seen.has(i),'DUAL_ENTRY');seen.add(i);sum+=weight;const p=pose(fj.poses[i],true);for(const g of groups)if(lt(g.rect[0][0],p.C[0])&&lt(p.C[0],g.rect[0][1])&&lt(g.rect[1][0],p.C[1])&&lt(p.C[1],g.rect[1][1]))loads[g.id]+=weight;}need(sum===BigInt(m.expected_dual_sum),'RETAINED_DUAL_SUM');diagnostics.push({id:m.id,retained_mass_units:String(sum),scale:String(D),new_center_column_loads:loads.map(String)});}need(diagnostics.length===2,'TWO_RETAINED_DUALS');
 return{schema:'n17.c028.frontier-result.v1',scope:'exact outer-box components, capacity-one center columns, compatible pair witnesses, and reused finite-dual diagnostics',new_lower_bound:false,resolution:N,frontier_cells:cells.size,component_count:groups.length,components:groups.map(g=>({id:g.id,cell_count:g.keys.length,index_lo:g.lo,index_hi:g.hi,center_rectangle:g.rect.map(a=>a.map(String)),squared_diameter_margin:String(g.gap),witness_count:g.witnesses,cell_keys:g.keys})),witnesses:records,open_boundary_control:{open_capture:0,closed_capture:1},dual_diagnostics:diagnostics};
}
if(require.main===module)try{need(process.argv.length===7,'USAGE_SPEC_ATLAS_CASES_RETAINED_FINITE_FRESH_OUTPUT');const paths=process.argv.slice(2),op=paths.pop();need(!fs.existsSync(op),'FRESH_OUTPUT_REQUIRED');const r=main(...paths.map(p=>strictParse(fs.readFileSync(p,'utf8'))));fs.writeFileSync(op,JSON.stringify(r)+'\n',{flag:'wx'});console.log('PASS_FRONTIER_COMPONENTS_AND_WITNESSES components='+r.component_count+' witnesses='+r.witnesses.length);}catch(e){console.error('REJECT '+e.message);process.exit(1);}
module.exports={main};
