// Exact connected-box grouping, capacity-one center rectangles, and real witnesses.
#include "common.hpp"
#include <queue>
#include <map>
static Q rq(const std::string&s){return qr(s.find('/')==std::string::npos?s+"/1":s);}
static Pose retained_pose(const J&j){return {{rq(j.get<std::string>("cx")),rq(j.get<std::string>("cy"))},rq(j.get<std::string>("t"))};}
static Q gap(const Pose&a,const Q&A,const Pose&b,const Q&B){V u=frame(a.t),v=frame(b.t);Q best=-Q(1000000);for(V n:{u,perp(u),v,perp(v)})best=qmax(best,qa(dot(n,a.c-b.c))-radius(a,A,n)-radius(b,B,n));return best;}
static std::array<int,3> decode(const std::string&p,int depth){need(int(p.size())==depth,"FRONTIER_PATH_LENGTH");std::array<int,3> c{};for(int i=0;i<depth;i++){need(p[i]=='0'||p[i]=='1',"FRONTIER_PATH_BITS");c[i%3]=2*c[i%3]+p[i]-'0';}return c;}
struct Group {std::vector<int> keys;std::array<int,3>lo,hi;std::array<Q,2>xminmax,yminmax;Q diameter_gap;int witnesses=0;};
int main(int argc,char**argv){try{
 need(argc==6,"USAGE_SPEC_ATLAS_CASES_RETAINED_FINITE_FRESH_OUTPUT");need(!std::filesystem::exists(argv[5]),"FRESH_OUTPUT_REQUIRED");J sj=readj(argv[1]),aj=readj(argv[2]),wj=readj(argv[3]),fj=readj(argv[4]);
 need(sj.get<std::string>("schema")=="n17.c028.second-anchor-atlas.v2"&&aj.get<std::string>("schema")=="n17.c028.atlas-result.v2","ATLAS_SCHEMA");need(wj.get<std::string>("schema")=="n17.c028.frontier-witnesses.v1","WITNESS_SCHEMA");
 Q L=getq(sj,"L"),T=getq(sj,"cap"),A=L/T;need(getq(aj,"cap")==T&&getq(aj,"parent_side")==A,"TARGET_IDENTITY");int depth=aj.get<int>("max_depth");need(depth==sj.get<int>("max_depth")&&depth>=3&&depth<=21&&depth%3==0,"BALANCED_GRID_DEPTH");int N=1<<(depth/3);
 auto rr=ja(aj.get_child("root"));need(rr.size()==3,"ROOT_SHAPE");std::array<Q,3> low,high;for(int d=0;d<3;d++){auto v=ja(rr[d]);need(v.size()==2,"ROOT_SHAPE");low[d]=qr(v[0].data());high[d]=qr(v[1].data());need(low[d]<high[d],"ROOT_ORDER");}
 Q nt=getq(sj,"near_t");need(low[0]==A/Q(2)&&low[1]==A/Q(2)&&high[0]==L-A/Q(2)&&high[1]==L-A/Q(2)&&low[2]==nt&&high[2]==(Q(1)-nt)/(Q(1)+nt),"ROOT_IDENTITY");
 auto encode=[&](const std::array<int,3>&c){return(c[0]*N+c[1])*N+c[2];};auto coords=[&](int k){return std::array<int,3>{k/(N*N),(k/N)%N,k%N};};
 std::set<int> cells;std::map<std::string,int> path_key;for(auto&p:ja(aj.get_child("frontier_paths"))){auto path=p.data();int k=encode(decode(path,depth));need(cells.insert(k).second&&path_key.emplace(path,k).second,"DUPLICATE_FRONTIER_CELL");}need(cells.size()==size_t(aj.get<long long>("counts.unresolved"))&&!cells.empty(),"FRONTIER_COUNT");
 std::set<int> left=cells;std::vector<Group> groups;std::map<int,int> owner;
 while(!left.empty()){
  int first=*left.begin();left.erase(first);std::queue<int> todo;todo.push(first);Group g;g.lo={N,N,N};g.hi={-1,-1,-1};
  while(!todo.empty()){int k=todo.front();todo.pop();g.keys.push_back(k);auto c=coords(k);for(int d=0;d<3;d++){g.lo[d]=std::min(g.lo[d],c[d]);g.hi[d]=std::max(g.hi[d],c[d]);}
   for(int a=-1;a<=1;a++)for(int b=-1;b<=1;b++)for(int t=-1;t<=1;t++){if(a==0&&b==0&&t==0)continue;std::array<int,3> z{c[0]+a,c[1]+b,c[2]+t};if(z[0]<0||z[1]<0||z[2]<0||z[0]>=N||z[1]>=N||z[2]>=N)continue;int q=encode(z);auto it=left.find(q);if(it!=left.end()){left.erase(it);todo.push(q);}}
  }
  std::sort(g.keys.begin(),g.keys.end());Q pad=A/Q(1000000);g.xminmax={low[0]+(high[0]-low[0])*Q(g.lo[0],N)-pad,low[0]+(high[0]-low[0])*Q(g.hi[0]+1,N)+pad};g.yminmax={low[1]+(high[1]-low[1])*Q(g.lo[1],N)-pad,low[1]+(high[1]-low[1])*Q(g.hi[1]+1,N)+pad};Q dx=g.xminmax[1]-g.xminmax[0],dy=g.yminmax[1]-g.yminmax[0];g.diameter_gap=A*A-dx*dx-dy*dy;need(g.diameter_gap>Q(0),"COMPONENT_NOT_CAPACITY_ONE");for(int k:g.keys)owner[k]=int(groups.size());groups.push_back(g);
 }
 Pose anc=pose(wj.get_child("anchor"));need(fits(anc,A,L),"ILLEGAL_ANCHOR");auto raw=sj.get_child("anchor");Pose ra=pose(raw);need(qa(anc.c.x-ra.c.x)<=getq(raw,"ex")&&qa(anc.c.y-ra.c.y)<=getq(raw,"ey")&&qa(anc.t-ra.t)<=getq(raw,"et"),"ANCHOR_OUTSIDE_RAW_BOX");
 Q alpha=Q(1)-getq(sj,"epsilon"),step=(T-Q(2)*alpha)/Q(3);std::vector<V> grid;for(int y=0;y<4;y++)for(int x=0;x<4;x++)grid.push_back({A*(alpha+Q(x)*step),A*(alpha+Q(y)*step)});
 std::vector<std::string> records;std::set<std::string> names;
 for(auto&w:ja(wj.get_child("witnesses"))){std::string id=w.get<std::string>("id"),path=w.get<std::string>("frontier_path");need(names.insert(id).second,"DUPLICATE_WITNESS");need(path_key.count(path),"WITNESS_NOT_IN_FRONTIER");Pose p=pose(w.get_child("pose"));need(p.t>=Q(0)&&p.t<=Q(1)&&fits(p,A,L),"ILLEGAL_WITNESS");Q sep=gap(p,A,anc,A);need(sep>Q(0),"WITNESS_OVERLAP");
  auto c=coords(path_key.at(path));std::array<Q,3>v{p.c.x,p.c.y,p.t};for(int d=0;d<3;d++){Q lo=low[d]+(high[d]-low[d])*Q(c[d],N),hi=low[d]+(high[d]-low[d])*Q(c[d]+1,N);need(lo<=v[d]&&v[d]<=hi,"WITNESS_OUTSIDE_CELL");}
  Q avoid=Q(1000);for(V z:grid){Q m=-point_margin(p,A,z);need(m>Q(0),"WITNESS_CAPTURES_GRID");avoid=qmin(avoid,m);}
  auto h=ja(w.get_child("halfwidths"));need(h.size()==3,"BOX_WIDTH_DIMENSION");Q ex=qr(h[0].data()),ey=qr(h[1].data()),et=qr(h[2].data());need(ex>Q(0)&&ey>Q(0)&&et>Q(0)&&p.t-et>=Q(0)&&p.t+et<=Q(1),"BOX_WIDTH_RANGE");Q out=A*(Q(1)+Q(2)*et)+Q(2)*(ex+ey);need(fits(p,out,L),"BOX_WALL");Q outgap=gap(p,out,anc,A);need(outgap>Q(0),"BOX_OVERLAP");Q outavoid=Q(1000);for(V z:grid){Q v=-point_margin(p,out,z);need(v>Q(0),"BOX_CAPTURES_GRID");outavoid=qmin(outavoid,v);}
  int group=owner.at(path_key.at(path));groups[group].witnesses++;std::ostringstream o;o<<"{\"id\":"<<quoted(id)<<",\"component\":"<<group<<",\"path\":"<<quoted(path)<<",\"separation_margin\":"<<quoted(qs(sep))<<",\"grid_avoidance_margin\":"<<quoted(qs(avoid))<<",\"outer_side\":"<<quoted(qs(out))<<",\"outer_separation_margin\":"<<quoted(qs(outgap))<<",\"outer_grid_avoidance_margin\":"<<quoted(qs(outavoid))<<'}';records.push_back(o.str());
 }
 need(wj.get<bool>("open_boundary_control"),"BOUNDARY_CONTROL_REQUIRED");Pose corner{{A/Q(2),A/Q(2)},Q(0)};int open=0,closed=0;Q oldstep=(T-Q(2))/Q(3);for(int y=0;y<4;y++)for(int x=0;x<4;x++){Q m=point_margin(corner,A,{A*(Q(1)+Q(x)*oldstep),A*(Q(1)+Q(y)*oldstep)});open+=m>Q(0);closed+=m>=Q(0);}need(open==0&&closed==1,"OPEN_BOUNDARY_CONTROL");
 need(fj.get<std::string>("schema")=="n17.c026.exact-finite-comparison.v1"&&rq(fj.get<std::string>("target"))==T,"RETAINED_DUAL_INPUT");auto poses=ja(fj.get_child("poses"));Z D=zi(fj.get<std::string>("scale"));need(D>0,"SCALE");std::vector<std::string> dualrows;
 for(auto&m:ja(fj.get_child("models"))){std::string id=m.get<std::string>("id");if(id!="full_40_point_basis"&&id!="matched_segment_cliques")continue;std::vector<Z>loads(groups.size());std::set<int>seen;Z sum=0;for(auto&e:ja(m.get_child("dual"))){int i=e.get<int>("row");Z weight=zi(e.get<std::string>("units"));need(i>=0&&i<int(poses.size())&&i<m.get<int>("training_count")&&weight>0&&seen.insert(i).second,"DUAL_ENTRY");sum+=weight;Pose p=retained_pose(poses[i]);for(size_t k=0;k<groups.size();k++){auto&g=groups[k];if(g.xminmax[0]<p.c.x&&p.c.x<g.xminmax[1]&&g.yminmax[0]<p.c.y&&p.c.y<g.yminmax[1])loads[k]+=weight;}}
  need(sum==zi(m.get<std::string>("expected_dual_sum")),"RETAINED_DUAL_SUM");std::ostringstream o;o<<"{\"id\":"<<quoted(id)<<",\"retained_mass_units\":"<<quoted(sum.convert_to<std::string>())<<",\"scale\":"<<quoted(D.convert_to<std::string>())<<",\"new_center_column_loads\":[";for(size_t k=0;k<loads.size();k++){if(k)o<<',';o<<quoted(loads[k].convert_to<std::string>());}o<<"]}";dualrows.push_back(o.str());
 }
 need(dualrows.size()==2,"TWO_RETAINED_DUALS");std::ostringstream o;o<<"{\"schema\":\"n17.c028.frontier-result.v1\",\"scope\":\"exact outer-box components, capacity-one center columns, compatible pair witnesses, and reused finite-dual diagnostics\",\"new_lower_bound\":false,\"resolution\":"<<N<<",\"frontier_cells\":"<<cells.size()<<",\"component_count\":"<<groups.size()<<",\"components\":[";
 for(size_t k=0;k<groups.size();k++){if(k)o<<',';auto&g=groups[k];o<<"{\"id\":"<<k<<",\"cell_count\":"<<g.keys.size()<<",\"index_lo\":["<<g.lo[0]<<','<<g.lo[1]<<','<<g.lo[2]<<"],\"index_hi\":["<<g.hi[0]<<','<<g.hi[1]<<','<<g.hi[2]<<"],\"center_rectangle\":[["<<quoted(qs(g.xminmax[0]))<<','<<quoted(qs(g.xminmax[1]))<<"],["<<quoted(qs(g.yminmax[0]))<<','<<quoted(qs(g.yminmax[1]))<<"]],\"squared_diameter_margin\":"<<quoted(qs(g.diameter_gap))<<",\"witness_count\":"<<g.witnesses<<",\"cell_keys\":[";for(size_t i=0;i<g.keys.size();i++){if(i)o<<',';o<<g.keys[i];}o<<"]}";}
 o<<"],\"witnesses\":[";for(size_t i=0;i<records.size();i++){if(i)o<<',';o<<records[i];}o<<"],\"open_boundary_control\":{\"open_capture\":0,\"closed_capture\":1},\"dual_diagnostics\":["<<dualrows[0]<<','<<dualrows[1]<<"]}";write_new(argv[5],o.str());std::cout<<"PASS_FRONTIER_COMPONENTS_AND_WITNESSES components="<<groups.size()<<" witnesses="<<records.size()<<'\n';return 0;
}catch(const std::exception&e){std::cerr<<"REJECT "<<e.what()<<'\n';return 1;}}
