#!/usr/bin/env python3
"""Render the purpose register of the eleven-square packet's receipts.

Every directory and top-level file under the packet's `receipts/` has a curated tier and
purpose below, kept by hand because only a reader can say why a run was kept. Everything
else in the register is derived from the receipts on each run: file counts, sizes, the
recorded status, and who binds each receipt. The binding sources are the composer's
registries (`FIXED`, `CAPTURE`, `PILOTS`, and the three files the composer pins), the
three execution inventories, citations by other receipts (by path, by result hash, and by
the hash of a stored object), and links from the review article's template and the
packet's guides.

Receipt text is every `.json`, `.jsonl`, `.sh`, `.txt`, `.md` and `.log` file, and every
`.json.gz` decoded, except a `.json.gz` larger than `LARGEST_SCANNED_GZIP` bytes on disk.
Those are retained source states rather than records of a run: the one today,
`capture-root-pilot/adaptive-source.json.gz`, decodes to 137 MB of pose rows and would
more than double the scan. The register names every file it did not read.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import textwrap
import zlib
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Any

import numpy as np
from strif import atomic_output_file

from devtools.check_n11_final_composition import REVIEWED_COMPLETE_EXCLUSION_INVENTORY
from devtools.inventory_n11_completion import CAPTURE, FIXED, RECEIPTS
from devtools.inventory_n11_exclusions import FIELD_SHA, MANIFEST_SHA, PILOTS

ROOT = Path(__file__).resolve().parents[1]
# The repository root, which every recorded execution path is relative to.
REPO = ROOT.parent
PACKET = RECEIPTS.parent
REGISTER = RECEIPTS / "README.md"
TEMPLATE = ROOT / "devtools" / "templates" / "n11-optimality-review-article.md"
GUIDES = (PACKET / "VALIDATION.md", PACKET / "README.md")
EXCLUSION_INVENTORY = "exclusion-inventory.json"
BASELINE_INVENTORY = "baseline-d4-cuts/baseline-execution-inventory.json"
FIELD_INVENTORY = "field-batch-a/field-coverage-inventory.json"
# Files the composer reads at a hash pinned in its own modules rather than in `FIXED`.
COMPOSER_PINNED_FILES = frozenset(
    {FIELD_SHA, MANIFEST_SHA, REVIEWED_COMPLETE_EXCLUSION_INVENTORY or ""} - {""}
)
# Keys under which the composer's own output files record the registry they composed.
COMPOSER_REGISTRY_KEYS = ("reviewed_receipt_sha256s", "reviewed_fixed_receipt_sha256s")
LARGEST_SCANNED_GZIP = 2_000_000
TEXT_SUFFIXES = (".json", ".jsonl", ".sh", ".txt", ".md", ".log")
NAMES_SHOWN = 3
WIDTH = 88

PATH_TOKEN = re.compile(rb"receipts/([A-Za-z0-9._-]+)")
HEX_NAME = re.compile(r"[0-9a-f]{64}")
HEX_FLAGS = bytes(1 if byte in b"0123456789abcdef" else 0 for byte in range(256))

TITLE = "Receipts of the Eleven-Square Optimality Packet"
PURPOSE = (
    (
        "A receipt is the record of one checker run: its verdict, the SHA-256 of every input "
        "object and of the checker's own bytes, the command and commit that produced it, and "
        "a replay script. The proof's composer reads a fixed set of receipts by hash and "
        "checks that their joins agree, so the composed proof can be re-verified in seconds "
        "without rerunning the geometry, whose 2.1 GB of upstream inputs are not in this "
        "repository. Git holds the evidence; the hashes bind it (OR-16)."
    ),
    (
        "Not every receipt is read by the composer. Some are the ancestry an accepted receipt "
        "cites as its input; some are controls that measure what a partial, refused or "
        "profiling run reports; some are superseded attempts kept beside their replacement "
        "so the record says why the replacement exists; some are data the checkers read; and "
        "two are the retained replacement components of the review of 2026-10-03, which "
        "stand beside the accepted components rather than in their place. The tier column "
        "says which, and the binding column says who reads it, derived from the receipts "
        "themselves."
    ),
    (
        "This file is generated by `packing/devtools/render_n11_receipts_register.py`; "
        "`packing/tests/test_n11_receipts_register.py` fails when a receipt is undocumented "
        "or the file is stale. Edit the curated purposes in the renderer, then rerun it."
    ),
)
FOOTER = """<!-- This document follows common-doc-guidelines.md.
See github.com/jlevy/practical-prose and review guidelines before editing.
-->"""

# Sort order of the register, with the one-line meaning the summary table shows.
TIERS = {
    "composed": "the composed proof reads it",
    "data": "source objects, manifests and inventories the checkers read",
    "replacement": "a retained checked replacement from the review of 2026-10-03",
    "ancestry": "an earlier run an accepted receipt cites as its provenance or input",
    "control": "a partial, refused or profiling run, incomplete by design",
    "attempt": "a superseded or aborted attempt kept beside its successor",
}
# Bindings meaning the composed proof reads the receipt, directly or through an inventory.
COMPOSER_READ = (
    "composer, pinned",
    "capture join",
    "pilot registry",
    "exclusion inventory",
    "baseline inventory",
    "field inventory",
)

FAMILIES = {
    "case-census": (
        "The authoritative list of the 2,184 cases, which family excludes each, and the "
        "1,931-case baseline the conditional cuts presuppose."
    ),
    "d4-independent": (
        "The sixteen-cell center cover, the 220-region four-view overlay, the 1,572 strict "
        "distance bans and the three finite searches of the symmetry lemma."
    ),
    "d4-incidence": (
        "Review S3's replacement for the final symmetry search: incidence propagation over "
        "all 648 source-triple combinations and one distance bound; beside the accepted "
        "search."
    ),
    "baseline-d4-cuts": (
        "The 1,931-case baseline execution inventory that the conditional cuts for cases "
        "2175 and 2176 and the partition of case 1383 take as their premise."
    ),
    "exclusion-inventory.json": (
        "The inventory of the 276 generic exclusions: which batch receipt executed each "
        "accepted case, bound by path and hash; the composer reads the summaries it names."
    ),
    "nonfield-manifest": (
        "The manifest of the 276 generic proposals, their recipes and object identities, "
        "which every nonfield batch cites."
    ),
    "nonfield-sources": (
        "The proposal source objects for the generic exclusions, stored by hash; the "
        "manifest cites them and the batch case receipts cite the manifest."
    ),
    "nonfield-batch": (
        "One execution of generic exclusions: each case file is one case's checked "
        "exclusion and summary.json is the batch; the exclusion inventory binds it."
    ),
    "nonfield-batch-unbound": (
        "An aborted or superseded attempt, or an executor control, kept as the record of "
        "why the reviewed batch that replaced it exists."
    ),
    "generic-case": (
        "A single-case pilot or completion run that the pilot registry names: the "
        "conditional completions of cases 2175 and 2176, the partition of case 1383, and "
        "the pilots that fixed the batch recipes."
    ),
    "generic-mask2095-intake": (
        "The complete independent replay of case 2095 that the paper's Figure 6 draws one "
        "row of."
    ),
    "field-batch-a": (
        "The receipts of the 46 accepted field certificates, the field inventory, and the "
        "minimal selection of 44 that the review of 2026-10-03 added."
    ),
    "field-check": (
        "A dedicated or shared-runner check of one field certificate; the paper's "
        "charge-budget section and the validation guide's portable commands cite the "
        "mask-0 runs, and the field inventory binds the rest."
    ),
    "capture-root-round-final": (
        "Root round {round} of fourteen: one parallel ownership update of all eleven owners "
        "from the common prior; capture-root-chain binds the fourteen by hash."
    ),
    "capture-root-round-attempt": (
        "A superseded attempt at root round {round}, kept beside its final run."
    ),
    "capture-root-chain": (
        "Binds the fourteen root rounds into one chain by hash; the composer reads it."
    ),
    "capture-root-pilot": (
        "The pilot ownership run whose adaptive source state and owner-2 results the three "
        "bridge receipts cite as their input; the largest receipt, 21 MB, kept because the "
        "accepted bridge's provenance points at it."
    ),
    "capture-root-bridge": (
        "The bridge from the root rounds to the first capture step; final2 is the accepted "
        "one the composer reads, the two before it are its ancestry."
    ),
    "capture-step0": (
        "The first capture transition, which the root node and every step-1 control cite."
    ),
    "capture-transition-row0": "A one-row geometry diagnostic of the first transition.",
    "capture-root-node-full-integer": (
        "The root node's full state, accepted and read by the composer."
    ),
    "capture-root-node-step1": (
        "Partial or prefix runs of the root node's first step that stop at a declared "
        "ceiling: controls showing what an incomplete run reports, not accepted states."
    ),
    "capture-branch-r1-full": (
        "The first branch node's full state, accepted and read by the composer."
    ),
    "capture-branch-r1-row0": "A one-row diagnostic of the first branch node.",
    "capture-child": (
        "One checked node of the ten-node capture ancestry, read by the composer and "
        "joined through the source graph."
    ),
    "capture-ancestry": (
        "The seven role-named packets of the publisher's capture ancestry and the refusal "
        "result that records what the public audit binding cannot establish."
    ),
    "capture-near-index": (
        "A diagnostic index of the near leaf's live rows, built for inspection; its own "
        "provenance claims no proof premise and nothing cites it."
    ),
    "source-graph": (
        "The checked rooted branch-assumption graph of the ten source nodes, which every "
        "capture child cites."
    ),
    "pose-inclusion": (
        "Every live pose domain of the near leaf fits the accepted local rectangle, "
        "conditional on those domains."
    ),
    "local-isolation": (
        "The accepted fixed-T local isolation: all 128 branches and 8,448 signed margins "
        "over the fitted 33-radius rectangle."
    ),
    "local-dual-residual": (
        "The weighted and focused objects of the local proof, stored by hash, and the "
        "selected exact dual residuals; local isolation and pose inclusion read the "
        "objects."
    ),
    "local-isolation-two-radius": (
        "Review S2's two-radius box, checked by the unchanged isolation audit through a "
        "wrapper that pins the variant; beside the accepted rectangle."
    ),
    "local-profile": "A profiling run of the local geometry generation, INCOMPLETE by design.",
    "center-partition-1383-indexed": (
        "The two-branch center partition that excludes case 1383, read through the pilot "
        "registry."
    ),
    "center-partition-1383-profile": "A profiling run of that partition, INCOMPLETE by design.",
    # The top-level files below were not in the 2026-10-03 brief; their lines are written
    # from the files' own fields and from the tools that wrote them.
    "completion-inventory.json": (
        "The completion inventory's output: every required exclusion and capture node "
        "mapped to its reviewed execution, without rerunning geometry; the final composer "
        "recomputes it rather than reading this copy."
    ),
    "final-composition.json": (
        "The final composer's receipt: all 2,180 exclusions and ten capture nodes composed "
        "over the eighteen receipts it pins by hash, with no pending obligation."
    ),
    "final-composition-open": (
        "An earlier run of the final composer at 2,147 accepted exclusions that refused "
        "and named its pending obligations; kept as the record of what the last 33 "
        "exclusions and the remaining capture nodes closed."
    ),
    "nonfield-reviewed-costs": (
        "Measured wall and CPU costs of seventeen reviewed nonfield batches, selected "
        "batches only; a cost record, not a proof premise."
    ),
    "reachable-selector-cost": (
        "A cProfile measurement of one hosted dependency-selector test before and after a "
        "fix; it concerns the repository's test selection, not the proof."
    ),
}


@dataclass(frozen=True)
class Entry:
    """The curated half of one register row."""

    tier: str
    family: str
    kept: str = ""
    round: int | None = None

    @property
    def purpose(self) -> str:
        text = FAMILIES[self.family]
        return text.format(round=self.round) if self.round is not None else text


def _entries() -> dict[str, Entry]:
    entries = {
        "case-census": Entry("composed", "case-census"),
        "d4-independent": Entry("composed", "d4-independent"),
        "d4-incidence": Entry("replacement", "d4-incidence"),
        "baseline-d4-cuts": Entry("data", "baseline-d4-cuts"),
        "exclusion-inventory.json": Entry("data", "exclusion-inventory.json"),
        "nonfield-manifest": Entry("data", "nonfield-manifest"),
        "nonfield-sources": Entry("data", "nonfield-sources"),
        "generic-mask2095-intake": Entry("composed", "generic-mask2095-intake"),
        "field-batch-a": Entry("data", "field-batch-a"),
        "capture-root-chain": Entry("composed", "capture-root-chain"),
        "capture-root-pilot": Entry("ancestry", "capture-root-pilot"),
        "capture-root-bridge": Entry("ancestry", "capture-root-bridge"),
        "capture-root-bridge-final": Entry("ancestry", "capture-root-bridge"),
        "capture-root-bridge-final2": Entry("composed", "capture-root-bridge"),
        "capture-step0": Entry("composed", "capture-step0"),
        "capture-transition-row0": Entry("control", "capture-transition-row0"),
        "capture-root-node-full-integer": Entry("composed", "capture-root-node-full-integer"),
        "capture-branch-r1-full": Entry("composed", "capture-branch-r1-full"),
        "capture-branch-r1-row0": Entry(
            "control",
            "capture-branch-r1-row0",
            "the one-row check run before the full r1 node",
        ),
        "capture-ancestry": Entry("ancestry", "capture-ancestry"),
        "capture-near-index": Entry(
            "control",
            "capture-near-index",
            "a diagnostic index whose provenance claims no proof premise",
        ),
        "source-graph": Entry("composed", "source-graph"),
        "pose-inclusion": Entry("composed", "pose-inclusion"),
        "local-isolation": Entry("composed", "local-isolation"),
        "local-dual-residual": Entry("data", "local-dual-residual"),
        "local-isolation-two-radius": Entry("replacement", "local-isolation-two-radius"),
        "local-profile": Entry(
            "control", "local-profile", "the profile run before the accepted local geometry"
        ),
        "center-partition-1383-indexed": Entry("composed", "center-partition-1383-indexed"),
        "center-partition-1383-profile": Entry(
            "control",
            "center-partition-1383-profile",
            "the profile run before the indexed partition",
        ),
        "completion-inventory.json": Entry("data", "completion-inventory.json"),
        "final-composition.json": Entry("composed", "final-composition.json"),
        "final-composition-open-2147.json": Entry(
            "attempt",
            "final-composition-open",
            "the refusal with four capture nodes still missing",
        ),
        "final-composition-open-2147-bound.json": Entry(
            "attempt",
            "final-composition-open",
            "the same refusal from a different composer revision",
        ),
        "final-composition-open-2147-nine-capture.json": Entry(
            "attempt",
            "final-composition-open",
            "the refusal with one capture node still missing",
        ),
        "nonfield-reviewed-costs-2147.json.gz": Entry(
            "data",
            "nonfield-reviewed-costs",
            "the source of the batch costs in docs/project/verification-tooling.md",
        ),
        "reachable-selector-cost.json": Entry(
            "control",
            "reachable-selector-cost",
            "the measurement session 164's record cites; no proof obligation reads it",
        ),
    }
    for name in (
        "field-mask612",
        "field-mask1155",
        "shared-field-mask0",
        "shared-field-mask202",
    ):
        entries[name] = Entry("composed", "field-check")
    for name in ("field-mask0", "field-mask202"):
        entries[name] = Entry("ancestry", "field-check")
    for name in (
        "nonfield-batch-1",
        "nonfield-batch-a1-degenerate",
        "nonfield-batch-a1-direct",
        "nonfield-batch-a1-integer",
        "nonfield-batch-a1-repeated",
        "nonfield-batch-a1-required",
        "nonfield-batch-a2-reviewed-1",
        "nonfield-batch-a2-reviewed-2",
        "nonfield-batch-a2-reviewed-3",
        "nonfield-batch-a3-reviewed",
        "nonfield-batch-a3-reviewed-2",
        "nonfield-batch-a3-reviewed-3",
        "nonfield-batch-a3-reviewed-4",
        "nonfield-batch-final-sequential",
        "nonfield-batch-final-single",
        "nonfield-batch-refined-1",
        "nonfield-batch-refined-2",
        "nonfield-batch-refined-retry",
    ):
        entries[name] = Entry("composed", "nonfield-batch")
    for name, successor in (
        ("nonfield-batch-a2-direct-1", "nonfield-batch-a2-reviewed-1"),
        ("nonfield-batch-a2-direct-2", "nonfield-batch-a2-reviewed-2"),
        ("nonfield-batch-a3-direct", "nonfield-batch-a3-reviewed"),
    ):
        entries[name] = Entry(
            "attempt",
            "nonfield-batch-unbound",
            f"the aborted run whose cases {successor} re-ran; `aborted.json` says why",
        )
    entries["nonfield-batch-a3-integer-1"] = Entry(
        "attempt",
        "nonfield-batch-unbound",
        "the superseded run whose 32 cases nonfield-batch-a3-reviewed-2 re-ran",
    )
    entries["nonfield-executor-worktree-control"] = Entry(
        "control",
        "nonfield-batch-unbound",
        "an executor control on case 2135, which the pilot registry credits elsewhere",
    )
    for name in (
        "generic-case1687-partner",
        "generic-case1723-chain",
        "generic-case1875-complete",
        "generic-case2053-refined",
        "generic-case2129-repeated",
        "generic-case2135-pilot",
        "generic-case2175-complete",
        "generic-case2176-complete",
    ):
        entries[name] = Entry("composed", "generic-case")
    for name in ("far2", "far13", "far15", "near", "near13", "r10", "r11", "r111"):
        entries[f"capture-child-{name}"] = Entry("composed", "capture-child")
    for name in (
        "integer",
        "prefix10-integer",
        "prefix10-reference",
        "reference-incomplete",
    ):
        entries[f"capture-root-node-step1-{name}"] = Entry(
            "control",
            "capture-root-node-step1",
            "a control showing what a run stopped at its declared ceiling reports",
        )
    for number in range(1, 15):
        entries[f"capture-root-round{number}-final"] = Entry(
            "ancestry", "capture-root-round-final", round=number
        )
    for number in (1, 2, 8, 12):
        entries[f"capture-root-round{number}-attempt1"] = Entry(
            "attempt",
            "capture-root-round-attempt",
            f"the record of why root round {number} was rerun",
            round=number,
        )
    return entries


ENTRIES = _entries()


@dataclass(frozen=True)
class Scan:
    """What one receipt's files say, read once."""

    name: str
    file_count: int
    size: int
    status: str | None
    sample: tuple[str, ...]
    result_sha256: frozenset[str]
    file_sha256: frozenset[str]
    objects: frozenset[str]
    names_cited: frozenset[str]
    hashes_cited: frozenset[str]
    registry: Mapping[str, str] | None
    unread: tuple[str, ...]


@dataclass(frozen=True)
class Binding:
    """Who binds one receipt, derived from the registries and the other receipts."""

    composer_pinned: bool
    capture_join: bool
    pilot_registry: bool
    exclusion_inventory: bool
    baseline_inventory: bool
    field_inventory: bool
    by_result_hash: tuple[str, ...]
    by_path: tuple[str, ...]
    by_object: tuple[str, ...]
    paper: bool
    validation_guide: bool

    def labels(self) -> list[str]:
        flags = (
            self.composer_pinned,
            self.capture_join,
            self.pilot_registry,
            self.exclusion_inventory,
            self.baseline_inventory,
            self.field_inventory,
        )
        labels = [label for label, flag in zip(COMPOSER_READ, flags, strict=True) if flag]
        for label, names in (
            ("cited by result hash:", self.by_result_hash),
            ("cited by path:", self.by_path),
            ("object held: cited by", self.by_object),
        ):
            if names:
                labels.append(f"{label} {shown(names)}")
        if self.paper:
            labels.append("paper")
        if self.validation_guide:
            labels.append("validation guide")
        return labels

    @property
    def composer_read(self) -> bool:
        return any(label in COMPOSER_READ for label in self.labels())

    @property
    def cited(self) -> bool:
        return bool(self.by_result_hash or self.by_path or self.by_object)


def shown(names: Sequence[str]) -> str:
    if len(names) <= NAMES_SHOWN:
        return ", ".join(names)
    return ", ".join(names[:NAMES_SHOWN]) + f" +{len(names) - NAMES_SHOWN} more"


def hashes_in(data: bytes) -> set[str]:
    """Every maximal run of exactly 64 lowercase hex digits, found without a regex.

    A regex pays per byte, and most of the decoded bytes here are long decimal numbers,
    which are hex digits too; marking runs with a byte table is about four times faster.
    """
    flags = np.frombuffer(b"\0" + data.translate(HEX_FLAGS) + b"\0", dtype=np.int8)
    edges = np.flatnonzero(np.diff(flags))
    starts, ends = edges[0::2], edges[1::2]
    return {data[start : start + 64].decode() for start in starts[ends - starts == 64].tolist()}


def names_in(data: bytes) -> set[str]:
    return {token.decode().rstrip(".") for token in PATH_TOKEN.findall(data)}


def decoded(path: Path, raw: bytes) -> bytes:
    return zlib.decompress(raw, wbits=31) if path.name.endswith(".gz") else raw


def is_text(path: Path) -> bool:
    return path.name.endswith((*TEXT_SUFFIXES, ".json.gz"))


def object_name(path: Path, receipt: Path) -> str | None:
    """The hex identity of a file stored under an `objects/` directory, if it has one."""
    stem = path.name.split(".", 1)[0]
    in_store = "objects" in path.relative_to(receipt).parts[:-1]
    return stem if in_store and HEX_NAME.fullmatch(stem) else None


def status_of(record: Any) -> str | None:
    status = record.get("status") if isinstance(record, dict) else None
    return status if isinstance(status, str) else None


def scan(name: str) -> Scan:
    path = RECEIPTS / name
    files = [path] if path.is_file() else sorted(p for p in path.rglob("*") if p.is_file())
    names: set[str] = set()
    hashes: set[str] = set()
    file_sha: set[str] = set()
    objects: set[str] = set()
    unread: list[str] = []
    for file in files:
        stored = object_name(file, path) if path.is_dir() else None
        if stored:
            objects.add(stored)
        if not is_text(file):
            continue
        if file.name.endswith(".gz") and file.stat().st_size > LARGEST_SCANNED_GZIP:
            unread.append(file.relative_to(RECEIPTS).as_posix())
            continue
        raw = file.read_bytes()
        file_sha.add(hashlib.sha256(raw).hexdigest())
        data = decoded(file, raw)
        names |= names_in(data)
        hashes |= hashes_in(data)
    result = path if path.is_file() else _result_file(path)
    record: Any = None
    result_sha: set[str] = set()
    if result is not None:
        raw = result.read_bytes()
        data = decoded(result, raw)
        result_sha = {hashlib.sha256(raw).hexdigest(), hashlib.sha256(data).hexdigest()}
        record = json.loads(data) if result.name.endswith((".json", ".json.gz")) else None
    registry = None
    if path.is_file() and isinstance(record, dict):
        registry = next((record[key] for key in COMPOSER_REGISTRY_KEYS if key in record), None)
    direct = sorted(p.name for p in path.iterdir() if p.is_file()) if path.is_dir() else []
    return Scan(
        name=name,
        file_count=len(files),
        size=sum(file.stat().st_size for file in files),
        status=status_of(record),
        sample=tuple((direct or [f.name for f in files])[:NAMES_SHOWN]),
        result_sha256=frozenset(result_sha),
        file_sha256=frozenset(file_sha),
        objects=frozenset(objects),
        names_cited=frozenset(names - {name}),
        hashes_cited=frozenset(hashes),
        registry=registry,
        unread=tuple(unread),
    )


def _result_file(directory: Path) -> Path | None:
    for candidate in ("result.json", "result.json.gz"):
        if (directory / candidate).is_file():
            return directory / candidate
    return None


def receipt_names() -> list[str]:
    """Every receipt on disk: each directory and each top-level file but this register."""
    return sorted(path.name for path in RECEIPTS.iterdir() if path != REGISTER)


def _receipt_of(recorded: str) -> str:
    return (REPO / recorded).resolve().relative_to(RECEIPTS.resolve()).parts[0]


def inventory_bound(relative: str, key: str) -> frozenset[str]:
    record = json.loads((RECEIPTS / relative).read_bytes())
    return frozenset(_receipt_of(row["path"]) for row in record[key])


@cache
def scans() -> dict[str, Scan]:
    return {name: scan(name) for name in receipt_names()}


@cache
def bindings() -> dict[str, Binding]:
    """Derive every receipt's binding from the registries and the other receipts' text."""
    every = scans()
    captured = {receipt for receipt, _, _ in CAPTURE.values()}
    piloted = {relative.split("/", 1)[0] for relative in PILOTS}
    exclusion = inventory_bound(EXCLUSION_INVENTORY, "execution_record_bindings")
    baseline = inventory_bound(BASELINE_INVENTORY, "execution_record_bindings")
    field = inventory_bound(FIELD_INVENTORY, "accepted_receipts")
    paper = names_in(TEMPLATE.read_bytes())
    guides = set().union(*(names_in(guide.read_bytes()) for guide in GUIDES))
    outputs = {name for name, item in every.items() if item.registry is not None}
    result: dict[str, Binding] = {}
    for name, item in every.items():
        pinned = name in FIXED or bool(item.file_sha256 & COMPOSER_PINNED_FILES)
        # A structured binding already says what its source file's citation would say.
        restated = {name}
        restated |= {EXCLUSION_INVENTORY} if name in exclusion else set()
        restated |= {"baseline-d4-cuts"} if name in baseline else set()
        restated |= {"field-batch-a"} if name in field else set()
        restated |= outputs if pinned else set()
        others = [other for other in every.values() if other.name not in restated]
        by_hash = [o.name for o in others if o.hashes_cited & item.result_sha256]
        by_path = [o.name for o in others if name in o.names_cited and o.name not in by_hash]
        by_object = [
            o.name
            for o in others
            if o.hashes_cited & (item.objects - o.objects)
            and o.name not in by_hash
            and o.name not in by_path
        ]
        result[name] = Binding(
            composer_pinned=pinned,
            capture_join=name in captured,
            pilot_registry=name in piloted,
            exclusion_inventory=name in exclusion,
            baseline_inventory=name in baseline,
            field_inventory=name in field,
            by_result_hash=tuple(by_hash),
            by_path=tuple(by_path),
            by_object=tuple(by_object),
            paper=name in paper,
            validation_guide=name in guides,
        )
    return result


def tier_contradictions() -> dict[str, str]:
    """Curated tiers that the derived bindings contradict, with the reason for each."""
    found: dict[str, str] = {}
    every = scans()
    for name, entry in ENTRIES.items():
        binding = bindings().get(name)
        if binding is None:
            continue
        current_output = every[name].registry == FIXED
        if entry.tier == "composed" and not (binding.composer_read or current_output):
            found[name] = "curated composed, but nothing the composer reads binds it"
        elif entry.tier in {"attempt", "control", "replacement", "ancestry"} and (
            binding.composer_read
        ):
            found[name] = f"curated {entry.tier}, but the composer reads it"
        elif entry.tier == "ancestry" and not binding.cited:
            found[name] = "curated ancestry, but no other receipt cites it"
    return found


def size_text(size: int) -> str:
    return f"{size / 1e6:.1f} MB" if size >= 1_000_000 else f"{size / 1e3:.1f} KB"


def bound_text(name: str) -> str:
    labels = bindings()[name].labels()
    if labels:
        return "; ".join(labels)
    return f"**nothing**; kept as {ENTRIES[name].kept}"


def status_text(item: Scan) -> str:
    if item.status:
        return f"`{item.status}`"
    if (RECEIPTS / item.name).is_file():
        return "—"
    return ", ".join(f"`{name}`" for name in item.sample)


def link(name: str) -> str:
    return f"[`{name}/`]({name}/)" if (RECEIPTS / name).is_dir() else f"[`{name}`]({name})"


def ordered(names: Iterable[str]) -> list[str]:
    order = list(TIERS)
    return sorted(names, key=lambda name: (order.index(ENTRIES[name].tier), name))


def tier_table() -> list[str]:
    every = scans()
    rows = ["| Tier | What it is | Receipts | Size |", "| --- | --- | ---: | ---: |"]
    for tier, meaning in TIERS.items():
        members = [name for name in every if ENTRIES[name].tier == tier]
        size = sum(every[name].size for name in members)
        rows.append(f"| {tier} | {meaning} | {len(members)} | {size_text(size)} |")
    total = sum(item.size for item in every.values())
    rows.append(f"| **all** | | {len(every)} | {size_text(total)} |")
    return rows


def receipt_table() -> list[str]:
    every = scans()
    rows = [
        "| Receipt | Tier | Purpose | Status | Files | Size | Bound by |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    for name in ordered(every):
        item, entry = every[name], ENTRIES[name]
        rows.append(
            f"| {link(name)} | {entry.tier} | {entry.purpose} | {status_text(item)} | "
            f"{item.file_count} | {size_text(item.size)} | {bound_text(name)} |"
        )
    return rows


def legend() -> list[str]:
    unread = [path for item in scans().values() for path in item.unread]
    unread_text = ", ".join(f"`{path}`" for path in unread) or "none"
    items = (
        (
            "**composer, pinned**: the final composer reads it at a hash fixed in its own "
            "modules: `FIXED` in `packing/devtools/inventory_n11_completion.py`, or the pinned "
            "field inventory, nonfield manifest and exclusion inventory."
        ),
        (
            "**capture join** and **pilot registry**: `CAPTURE` or `PILOTS` in the same "
            "modules names it as one capture node's or one case's accepted execution."
        ),
        (
            "**exclusion inventory**, **baseline inventory**, **field inventory**: a recorded "
            "execution path in `exclusion-inventory.json`, "
            "`baseline-d4-cuts/baseline-execution-inventory.json` or "
            "`field-batch-a/field-coverage-inventory.json` falls inside it."
        ),
        (
            "**cited by result hash** and **cited by path**: another receipt's text contains "
            "the SHA-256 of its `result.json` (stored or decoded; for a top-level file, the "
            "file itself), or the path `receipts/<name>`."
        ),
        (
            "**object held**: another receipt cites, by hash, an object stored under its "
            "`objects/` that the citer does not store itself."
        ),
        (
            "**paper** and **validation guide**: the review article's template, or the "
            "packet's `VALIDATION.md` or `README.md`, links it."
        ),
    )
    notes = (
        "Each citing receipt is listed once, under the strongest relation, and a citation "
        "that only restates a structured binding, such as the inventory naming a batch or "
        "the composer's own output files, is not repeated. Text means every `.json`, "
        "`.jsonl`, `.sh`, `.txt`, `.md` and `.log` file and every `.json.gz` decoded; a "
        "`.json.gz` over 2 MB on disk is a retained source state, not a record of a run, "
        f"and is not read. Not read: {unread_text}."
    )
    lines = [wrap(f"- {item}", indent="  ") for item in items]
    return ["\n".join(lines), wrap(notes)]


def wrap(text: str, indent: str = "") -> str:
    return textwrap.fill(
        text,
        width=WIDTH,
        subsequent_indent=indent,
        break_long_words=False,
        break_on_hyphens=False,
    )


def render() -> str:
    parts = [f"# {TITLE}", *(wrap(paragraph) for paragraph in PURPOSE)]
    parts += ["## Tiers", "\n".join(tier_table())]
    parts += ["## Receipts", "\n".join(receipt_table())]
    parts += ["## How the Binding Column Is Derived", *legend()]
    parts.append(FOOTER)
    return "\n\n".join(parts) + "\n"


def parser() -> argparse.ArgumentParser:
    command = argparse.ArgumentParser(description=__doc__)
    command.add_argument("--check", action="store_true", help="fail if the register is stale")
    return command


def main(argv: Sequence[str] | None = None) -> int:
    arguments = parser().parse_args(argv)
    missing = sorted(set(receipt_names()) - set(ENTRIES))
    if missing:
        print(f"receipts without a curated entry: {', '.join(missing)}", file=sys.stderr)
        return 1
    expected = render()
    current = REGISTER.read_text(encoding="utf-8") if REGISTER.exists() else ""
    if arguments.check:
        if current != expected:
            print("receipts/README.md is stale; rerun the renderer", file=sys.stderr)
            return 1
        print("  n11 receipts register matches the receipts")
        return 0
    if current != expected:
        with atomic_output_file(REGISTER) as temporary:
            temporary.write_text(expected, encoding="utf-8")
        print("rendered n11 receipts register")
    else:
        print("n11 receipts register already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
