#!/usr/bin/env python3
"""Generate `frontier/VERIFIERS.md`: every verification program, whose it is, and what it backs.

`frontier/verifiers.yaml` is the record and `epistemics.md` (Confirmation) owns the
vocabulary. This view lists each program the evidence register names, external or
first-party, with its author, language, method, role, the digests or revisions that ran
and the retained paths that hold its source, and then every evidence entry that names
it, who ran that entry, how its code stands to the code the result's producer used
(`relationship_to_generator`), and the results that cite it. The gate fails when the
committed view drifts from the records.

Usage, from `packing/`:
    uv run --frozen --all-extras --group dev python -m devtools.render_verifiers --update
    uv run --frozen --all-extras --group dev python -m devtools.render_verifiers --check
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from strif import atomic_output_file

from devtools.verifier_registry import (
    EXTERNAL,
    FIRST_PARTY,
    LABELS,
    LEGEND,
    REGISTRY,
    SHORT_LABELS,
    Verifier,
    load,
    run_label,
)
from sqpack.yamlio import safe_load

ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "frontier" / "evidence.yaml"
RESULTS = ROOT / "frontier" / "results.yaml"
OUTPUT = ROOT / "frontier" / "VERIFIERS.md"
#: How far a view's link climbs from `packing/frontier/` to the repository root.
TO_REPO = "../../"
#: How many hexadecimal digits of a digest or revision the view prints; the record keeps
#: the whole value.
SHORT_HEX = 12
#: A program's name up to its first clause, a comma outside parentheses.
_FIRST_CLAUSE = re.compile(r",(?![^()]*\))")

BANNER = (
    "<!-- GENERATED by devtools.render_verifiers --update from verifiers.yaml, "
    "evidence.yaml and results.yaml. Do not edit. -->"
)

HEADER = """# Verifiers

{banner}

Every verification program the evidence register names: the checker each source says it
verified a result with, every program run here or by a third party to confirm one, and
the premise checks that ride with them.
A program is *external* when it was written outside this repository, by a result's
producer or another party, and *first-party* when it was written here.
It *decides* when it decides the claim of the evidence that runs it, and checks
*premises* when it verifies inputs, digests, receipts or a sample and leaves the decision
to another program.

Each evidence entry says how the code that verified it stands to the code its result's
producer used ([`epistemics.md`](../../epistemics.md#confirmation)):

- *{same}*: the producer's own checker ran, or, for this project's results, the code
  that produced them;
- *{shared}*: separately written code reused named parts of it;
- *{independent}*: code that shares none of it decided the claim.

A replay with the producer's code establishes that the result reproduces, not that a
second implementation agrees.
[`RESULTS.md`](RESULTS.md#verification-code) lists the programs behind each result.
"""


def _link(path: str) -> str:
    return f"[`{path}`]({TO_REPO}{path})"


def _version(version: Mapping[str, Any]) -> str:
    parts = []
    if "sha256" in version:
        parts.append(f"SHA-256 `{str(version['sha256'])[:SHORT_HEX]}…`")
    if "revision" in version:
        parts.append(f"revision `{str(version['revision'])[:SHORT_HEX]}`")
    text = ", ".join(parts)
    notes = [str(version[key]) for key in ("note",) if key in version]
    if "path" in version:
        notes.append(f"of `{Path(str(version['path'])).name}`")
    return f"{text} ({'; '.join(notes)})" if notes else text


def citing_results(results: Sequence[Mapping[str, Any]]) -> dict[str, list[str]]:
    """The results that cite each evidence entry, by evidence id."""
    cited: dict[str, list[str]] = {}
    for record in results:
        for ref in record["evidence"]:
            cited.setdefault(ref, []).append(str(record["id"]))
    return cited


def program_section(
    verifier: Verifier, entries: Sequence[Mapping[str, Any]], cited: Mapping[str, list[str]]
) -> list[str]:
    """One program's section: what it is, whose, which versions ran, and what it backs."""
    record = verifier.record
    facts = " · ".join(
        (
            verifier.author,
            verifier.provenance,
            "decides" if verifier.decides else "checks premises",
            ", ".join(record["language"]),
            ", ".join(record["methods"]),
        )
    )
    lines = [
        f"### `{verifier.id}`",
        "",
        f"**{verifier.program}** · {facts}",
        "",
        " ".join(str(record["summary"]).split()),
        "",
        "- Source: " + ", ".join(_link(path) for path in record["source"]),
    ]
    if versions := record.get("versions"):
        lines.append("- Versions run: " + "; ".join(_version(version) for version in versions))
    else:
        lines.append("- Versions run: this repository's commits, which Git holds")
    if independence := record.get("independence_record"):
        lines.append(f"- What its authors read and used: {_link(str(independence))}")
    if note := record.get("note"):
        lines.append(f"- Note: {' '.join(str(note).split())}")
    lines.append("")
    backed = [entry for entry in entries if verifier.id in (entry.get("verifiers") or [])]
    if not backed:
        lines += ["No evidence entry names it yet.", ""]
        return lines
    lines += [
        "| evidence | run | code | results |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{entry['id']}` | {run_label(entry)} "
        f"| {SHORT_LABELS.get(str(entry.get('relationship_to_generator')), '-')} "
        f"| {', '.join(cited.get(str(entry['id']), [])) or '-'} |"
        for entry in backed
    )
    lines.append("")
    return lines


def render() -> str:
    verifiers = load(REGISTRY)
    entries = safe_load(EVIDENCE.read_text(encoding="utf-8"))["evidence"]
    results = safe_load(RESULTS.read_text(encoding="utf-8"))["results"]
    cited = citing_results(results)
    usage = Counter(v for entry in entries for v in entry.get("verifiers") or [])
    backed_results = {
        verifier_id: sorted(
            {
                rid
                for entry in entries
                if verifier_id in (entry.get("verifiers") or [])
                for rid in cited.get(str(entry["id"]), [])
            }
        )
        for verifier_id in verifiers
    }
    same, shared, independent = LEGEND
    lines = [
        HEADER.format(banner=BANNER, same=same, shared=shared, independent=independent),
        "## The Short Version",
        "",
    ]
    external = [v for v in verifiers.values() if v.provenance == EXTERNAL]
    first_party = [v for v in verifiers.values() if v.provenance == FIRST_PARTY]
    named = [entry for entry in entries if entry.get("verifiers")]
    relations = Counter(
        LABELS.get(str(entry.get("relationship_to_generator")), "relation not recorded")
        for entry in named
    )
    lines += [
        (
            f"- **{len(verifiers)}** programs: **{len(external)}** external and "
            f"**{len(first_party)}** first-party; "
            f"**{sum(v.decides for v in verifiers.values())}** decide claims and "
            f"**{sum(not v.decides for v in verifiers.values())}** check premises."
        ),
        (
            f"- **{len(named)}** of **{len(entries)}** evidence entries name the programs "
            "that verified them: "
            + ", ".join(
                f"{count} {label}"
                for label, count in sorted(relations.items(), key=lambda item: -item[1])
            )
            + "."
        ),
        "",
        "## Programs",
        "",
        "| id | program | author | provenance | role | evidence | results |",
        "| --- | --- | --- | --- | --- | ---: | ---: |",
    ]
    lines.extend(
        f"| [`{verifier.id}`](#{verifier.id.lower()}) "
        f"| {_FIRST_CLAUSE.split(verifier.program, maxsplit=1)[0]} "
        f"| {verifier.author} | {verifier.provenance} "
        f"| {'decides' if verifier.decides else 'premises'} "
        f"| {usage.get(verifier.id, 0)} | {len(backed_results[verifier.id])} |"
        for verifier in verifiers.values()
    )
    lines += ["", "## By Program", ""]
    for verifier in verifiers.values():
        lines.extend(program_section(verifier, entries, cited))
    lines += [
        "<!-- This document follows common-doc-guidelines.md.",
        "See github.com/jlevy/practical-prose and review guidelines before editing.",
        "-->",
        "",
    ]
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--update", action="store_true")
    group.add_argument("--check", action="store_true")
    options = parser.parse_args(argv)
    rendered = render()
    relative = OUTPUT.relative_to(ROOT.parent)
    if options.update:
        with atomic_output_file(OUTPUT) as temporary:
            temporary.write_text(rendered, encoding="utf-8")
        print(f"wrote {relative}")
        return 0
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
        print(f"{relative} is stale; run devtools.render_verifiers --update")
        return 1
    print(f"{relative} agrees with verifiers.yaml and evidence.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
