// Independent rational geometry and exactly bounded integer sweep for a D4 threshold cover.
const fs=require('fs'),crypto=require('crypto');const begin=Date.now();const file=process.argv[2],out=process.argv[3],from=Number(process.argv[4]||0),count=Number(process.argv[5]||1e9),audit=process.argv[6]==='audit';const raw=fs.readFileSync(file,'utf8');const d=JSON.parse(raw.replace(/([:\[,]\s*)(-?\d+)(?=\s*[,}\]])/g,'$1"$2"'));
const need=(v,s)=>{if(!v)throw Error(s)};const abs=a=>a<0n?-a:a;function gcd(a,b){a=abs(a);b=abs(b);while(b)[a,b]=[b,a%b];return a}function lcm(a,b){return a/gcd(a,b)*b}function q(a,b=1n){a=BigInt(a);b=BigInt(b);need(b!==0n,'denominator');if(b<0n){a=-a;b=-b}const g=gcd(a,b);return[a/g,b/g]}function p(s){const a=String(s).split('/');return q(a[0],a[1]||1)}function add(a,b){return q(a[0]*b[1]+b[0]*a[1],a[1]*b[1])}function sub(a,b){return add(a,[-b[0],b[1]])}function mul(a,b){return q(a[0]*b[0],a[1]*b[1])}function div(a,b){return q(a[0]*b[1],a[1]*b[0])}const cmp=(a,b)=>a<b?-1:a>b?1:0;const le=(a,b)=>a[0]*b[1]<=b[0]*a[1];const eq=(a,b)=>a[0]*b[1]===b[0]*a[1];const positive=a=>a[0]>0n;const str=a=>a.join('/');function floor(a,b){const r=a/b;return a<0n&&a%b!==0n?r-1n:r}const ceil=(a,b)=>-floor(-a,b);function trig(t){return[q(t[1]*t[1]-t[0]*t[0],t[1]*t[1]+t[0]*t[0]),q(2n*t[0]*t[1],t[1]*t[1]+t[0]*t[0])]}
const A=p(d.A),L=p(d.L),D=BigInt(d.coordinate_denominator),LD=L[0]*D/L[1];need(positive(A)&&le(A,L)&&d.normalized_target&&eq(div(L,A),p(d.normalized_target))&&eq(L,q(4613,1000))&&D>0n&&L[0]*D%L[1]===0n,'container/scale');let pts=[],pw=[];
for(const rr of d.point_orbits){const[x,y,w]=rr.map(BigInt);need(x>=0n&&x<=LD&&y>=0n&&y<=LD&&w>=0n,'orbit');const m=new Map();for(const[u,v]of[[x,y],[y,x]])for(const a of[u,LD-u])for(const b of[v,LD-v])m.set(`${a},${b}`,[a,b]);const oo=[...m.values()].sort((a,b)=>cmp(a[0],b[0])||cmp(a[1],b[1]));pts.push(...oo);pw.push(...oo.map(()=>Number(w)));}
const lookup=new Map(pts.map((p,i)=>[p.join(','),i]));need(lookup.size===pts.length,'distinct physical sites');let atoms=[],budget=pw.reduce((a,b)=>a+BigInt(b),0n),absolute=pw.reduce((a,b)=>a+BigInt(b),0n);
for(let i=0;i<pw.length;i++)if(pw[i])atoms.push([[i],pw[i]]);
function comb(n,k){if(k<0||k>n)return 0;let z=1;for(let j=1;j<=k;j++)z=z*(n+1-j)/j;return z}function combinations(a,k,start=0,acc=[],out=[]){if(acc.length===k){out.push([...acc]);return out}for(let i=start;i<=a.length-(k-acc.length);i++){acc.push(a[i]);combinations(a,k,i+1,acc,out);acc.pop()}return out}
// Weighted threshold expansion by exact Boolean Mobius inversion.
function weightedExpansion(co,k,rules=[]){const n=co.length;need(n<=20,'bounded Boolean rule');const v=Array.from({length:2**n},(_,mask)=>Number(rules.length?rules.some(w=>(mask&w)===w):co.reduce((z,a,j)=>z+((mask>>j)&1)*a,0)>=k));for(let j=0;j<n;j++)for(let mask=0;mask<v.length;mask++)if((mask>>j)&1)v[mask]-=v[mask^(1<<j)];const out=[];for(let mask=1;mask<v.length;mask++)if(v[mask])out.push([Array.from({length:n},(_,j)=>j).filter(j=>(mask>>j)&1),v[mask]]);return out;}
for(const g of d.threshold_orbits){
 const w=BigInt(g.weight),k=Number(g.threshold),ss=g.sets.map(s=>s.map(Number)),n=ss[0].length,co=g.coefficients?g.coefficients.map(Number):Array(n).fill(1),total=co.reduce((z,a)=>z+a,0);
 need(w>=0n&&Number.isSafeInteger(k)&&k>=1&&k<=total&&co.length===n&&co.every((a,i)=>Number.isSafeInteger(a)&&a>0&&(i===0||co[i-1]>=a))&&Number.isSafeInteger(total),'weighted threshold');
 for(const ss0 of ss)need(ss0.length===n&&new Set(ss0).size===n&&ss0.every(i=>Number.isInteger(i)&&i>=0&&i<pts.length),'set');
 const rules=(g.winning_masks||[]).map(Number);need(!rules.length||(n<=12&&new Set(rules).size===rules.length&&rules.every(w=>Number.isInteger(w)&&w>0&&w<2**n)&&rules.every(a=>rules.every(b=>(a&b)!==0))),'valid intersecting rule');
 const canonical=ids=>rules.length?ids.join(','):ids.map((i,j)=>[co[j],i]).sort((a,b)=>b[0]-a[0]||a[1]-b[1]).map(z=>z[1]).join(',');
 const expected=new Set();
 for(const swap of[false,true])for(const sx of[false,true])for(const sy of[false,true]){
  const im=ss[0].map(i=>{let[x,y]=pts[i];if(swap)[x,y]=[y,x];if(sx)x=LD-x;if(sy)y=LD-y;const j=lookup.get(`${x},${y}`);need(j!==undefined,'D4 sites');return j});expected.add(canonical(im));
 }
 need(new Set(ss.map(canonical)).size===ss.length&&expected.size===ss.length&&ss.every(s=>expected.has(canonical(s))),'complete weighted D4 feature orbit');
 budget+=w*BigInt(ss.length*(rules.length?1:Math.floor(total/k)));const expansion=weightedExpansion(co,k,rules);
 for(const s of ss)for(const[pos,coefficient]of expansion){atoms.push([pos.map(j=>s[j]),Number(w)*coefficient]);absolute+=w*BigInt(Math.abs(coefficient));}
}
need(budget===BigInt(d.budget_units)&&absolute<2n**50n,'exact budget / safe integer bound');const required=BigInt(d.minimum_units);need(budget<17n*required,'counting contradiction');const entries=d.entries;let cursor=q(0),jobs=[];
for(let i=0;i<entries.length;i++){const[a,b,t,B]=entries[i].map(p);need(eq(a,cursor)&&le(q(0),a)&&!eq(a,b)&&le(a,b)&&le(b,q(1))&&!eq(b,q(1))&&positive(B)&&le(B,A)&&!eq(B,A),'interval chain');need(le(q(0),t)&&le(t,q(1))&&!eq(t,q(1)),'midpoint angle');const[c,s]=trig(t);let f=[],support=[];for(const u of[a,b]){const[cu,su]=trig(u),dot=add(mul(c,cu),mul(s,su));let cross=sub(mul(c,su),mul(s,cu));cross=[abs(cross[0]),cross[1]];need(positive(dot)&&le(cross,dot),'angular span');f.push(add(cu,su));support.push(add(dot,cross));}const max=le(support[0],support[1])?support[1]:support[0],min=le(f[0],f[1])?f[0]:f[1];need(positive(sub(A,mul(B,max))),'strict core');const r=mul(mul(A,min),q(1,2));need(le(mul(mul(B,add(c,s)),q(1,2)),r)&&le(r,mul(L,q(1,2))),'parent envelope');jobs.push([t,B,sub(mul(L,q(1,2)),r)]);cursor=b;}
need(positive(sub(add(mul(cursor,cursor),mul(q(2),cursor)),q(1))),'orientation coverage');
function bisect(a,v,right){let lo=0,hi=a.length;while(lo<hi){const mid=(lo+hi)>>1;if(a[mid]<v||(right&&a[mid]===v))lo=mid+1;else hi=mid}return lo}
function sweep(job){const[t,B,H]=job;const a=t[0],b=t[1],C=b*b-a*a,S=2n*a*b,T=b*b+a*a;let scale=lcm(lcm(2n*D,div(B,q(2))[1]),H[1]);const factor=scale/(2n*D),h=H[0]*(scale/H[1]),bh=div(B,q(2));const half=bh[0]*(scale/bh[1])*T;const uv=pts.map(([x,y])=>[(C*(2n*x-LD)+S*(2n*y-LD))*factor,(-S*(2n*x-LD)+C*(2n*y-LD))*factor]);const map=new Map();
 for(const[ids,w]of atoms){let u0=uv[ids[0]][0],u1=u0,v0=uv[ids[0]][1],v1=v0;for(const i of ids){const[u,v]=uv[i];if(u>u0)u0=u;if(u<u1)u1=u;if(v>v0)v0=v;if(v<v1)v1=v;}const r=[u0-half,u1+half,v0-half,v1+half];if(r[0]>=r[1]||r[2]>=r[3])continue;const key=r.join(',');let z=map.get(key);if(z)z[4]+=w;else map.set(key,[...r,w]);}
 const rect=[...map.values()].filter(r=>r[4]);const poly=[[-h,-h],[h,-h],[h,h],[-h,h]].map(([x,y])=>[C*x+S*y,-S*x+C*y]);const xs=new Set(poly.map(p=>p[0])),ys=new Set(poly.map(p=>p[1]));for(const r of rect){xs.add(r[0]);xs.add(r[1]);ys.add(r[2]);ys.add(r[3]);}const xe=[...xs].sort(cmp),ye=[...ys].sort(cmp),xi=new Map(xe.map((v,i)=>[v,i])),yi=new Map(ye.map((v,i)=>[v,i]));let events=Array.from({length:xe.length},()=>[]);for(const r of rect){const lo=yi.get(r[2]),hi=yi.get(r[3]);events[xi.get(r[0])].push([lo,hi,r[4]]);events[xi.get(r[1])].push([lo,hi,-r[4]]);}const edges=[];for(let k=0;k<4;k++){let[u,v]=poly[k],[z,w]=poly[(k+1)%4];if(z===u)continue;if(z<u){[u,z]=[z,u];[v,w]=[w,v];}edges.push([u,z,w-v,v*(z-u)-u*(w-v),z-u]);}const left=poly.reduce((v,p)=>p[0]<v?p[0]:v,poly[0][0]),right=poly.reduce((v,p)=>p[0]>v?p[0]:v,poly[0][0]);let n=1;while(n<ye.length-1)n*=2;const mn=new Float64Array(2*n),lazy=new Float64Array(2*n);
 function update(k,a,b,lo,hi,w){if(hi<=a||b<=lo)return;if(lo<=a&&b<=hi){mn[k]+=w;lazy[k]+=w;return}const mid=(a+b)>>1;update(2*k,a,mid,lo,hi,w);update(2*k+1,mid,b,lo,hi,w);mn[k]=lazy[k]+Math.min(mn[2*k],mn[2*k+1]);}
 function query(k,a,b,lo,hi){if(hi<=a||b<=lo)return Infinity;if(lo<=a&&b<=hi)return mn[k];const mid=(a+b)>>1;return lazy[k]+Math.min(query(2*k,a,mid,lo,hi),query(2*k+1,mid,b,lo,hi));}
 let best=Infinity,cells=0;for(let i=0;i<xe.length-1;i++){for(const[l,h,w]of events[i])update(1,0,n,l,h,w);const a=xe[i],b=xe[i+1];if(a<left||b>right)continue;const crossing=[];for(const[u,z,m,j,dd]of edges)if(u<=a&&b<=z){crossing.push([m*a+j,dd],[m*b+j,dd]);}need(crossing.length===4,'polygon crossings');let[bn,bd]=crossing[0],[tn,td]=crossing[0];for(const[v,z]of crossing){if(v*bd<bn*z){bn=v;bd=z}if(v*td>tn*z){tn=v;td=z}}const lo=bisect(ye,floor(bn,bd),true)-1,hi=bisect(ye,ceil(tn,td),false);need(lo>=0&&lo<hi&&hi<=ye.length-1,'query limits');const v=query(1,0,n,lo,hi);need(Number.isSafeInteger(v),'integer sweep');if(v<best)best=v;cells+=hi-lo;}
 return {minimum_units:String(best),cells};
}
const end=Math.min(entries.length,from+count),rows=[];for(let i=from;i<end;i++){const z=sweep(jobs[i]);rows.push({interval:i,...z});if(BigInt(z.minimum_units)<required&&!audit){const result={status:'EXACT_INTERVAL_COVERAGE_FAILURE',interval:i,...z,required:String(required),rows,certificate_sha256:crypto.createHash('sha256').update(raw).digest('hex'),seconds:(Date.now()-begin)/1000,verified_utc:new Date().toISOString()};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify(result));process.exit(2);}if((i-from)%64===0)console.log('EXACT_INTERVAL',i,z.minimum_units,(Date.now()-begin)/1000);}
const result={status:rows.some(r=>BigInt(r.minimum_units)<required)?'EXACT_INTERVAL_FAILURES_IN_PARTITION':from===0&&end===entries.length?'PASS_INDEPENDENT_GLOBAL_THRESHOLD_CERTIFICATE':'PASS_INDEPENDENT_INTERVAL_PARTITION',start:from,end_exclusive:end,total_intervals:entries.length,minimum_units:String(rows.reduce((a,r)=>BigInt(r.minimum_units)<a?BigInt(r.minimum_units):a,2n**60n)),budget_units:String(budget),required_units:String(required),rows,certificate_sha256:crypto.createHash('sha256').update(raw).digest('hex'),seconds:(Date.now()-begin)/1000,verified_utc:new Date().toISOString()};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({...result,rows:undefined}));
